### ISSUE TITLE
06 -- Game-of-Sticks -- Glenn Hurley

### ISSUE THREAD

**Issue by gmhurley** [tiyd-python-2015-08/assigments#102]
- [x] Blank slate
  - [x] Create a GitHub repo called `game-of-sticks`
  - [x] Put a `README.md` file in it and copy sticks.py and sticks_test.py from this repository into it.
- [ ] Normal Mode
  - [ ] Player vs Player
    - [x] Decide on the data structure(s) that you are going to need to use to represent the state of the game when played
    - [x] Decide on the tasks that will be part of the game loop
    - [ ] Write test functions for each of the tasks
    - [ ] Write functions for each of the tasks and make sure they pass your tests
  - [ ] Player vs AI
    - [x] Decide on the data structure(s) that you are going to need to use to represent the additional state of the artificial intelligence
    - [x] Write functions to assist with each of the tasks of the AI
    - [x] Modify your game loop/main funciton to allow for the AI to play
    - [x] Make sure that your AI actually does get better over time - play a few games against it. You may want to add some extra debugging output to keep an eye on the hats
- [ ] Hard Mode
  - [x] Modify your program to allow for AI to play against AI
  - [x] Give the human player the option to battle against the AI from normal mode or a pre-trained AI that has played a large number of simulated games
  - [ ] Examine the contents of the hats for the pre-trained AI, and see if you can determine its strategy
- [ ] Nightmare Mode
  - [ ] Write a Tic-Tac-Toe program that pre-trains its AI using the same strategy as **Hard Mode**.

**Comment by gmhurley** [comment]
@jamesmallen @powder-river 
Throwing in the towel for the night. I'm really lost on how to write tests with so much user input littered throughout my program. Hoping we can cover tomorrow am.

https://github.com/gmhurley/game-of-sticks

**Comment by powder-river** [comment]
@gmhurley let's chat today glenn about tests. also  I am not sure if you're ai is actually learning, I don't see where in your code that the computer is learning so you might need to point that out during lab today. It looks like playing against a computer or a human looks to work well.

**Comment by gmhurley** [comment]
@powder-river ... no problem. I was trying to follow:
http://stackoverflow.com/questions/11218477/how-can-i-use-pickle-to-save-a-dict
so save the dictionary I'm using to a file so the cpu wouldn't forget what it's already learned.

**Comment by gmhurley** [comment]
```
def update_ai_dict(player_type, ai_dict, ai_picks):
    """
    This function see which player won (human or computer) to make
    the correct update to the ai_dict that's stored as a pickle file.
    """
    if player_type == '2':
        for k, v in ai_picks.items():
            if k in (1, 2):
                continue
            elif len(ai_dict[k]) > 1:
                ai_dict[k].remove(v)
            else:
                ai_dict[k] = [(random.choice([1, 2, 3]))]
    else:
        for k, v in ai_picks.items():
            ai_dict[k].append(v)

    return ai_dict
```
