### ISSUE TITLE
06--Game of Sticks--Jermaine Kee

### ISSUE THREAD

**Issue by JermaineKee** [tiyd-python-2015-08/assigments#107]
- [x] Blank slate
  - [x] Create a GitHub repo called `game-of-sticks`
  - [x] Put a `README.md` file in it and create sticks.py and sticks_test.py.
- [x] Normal Mode
  - [x] Player vs Player
    - [x] Decide on the data structure(s) that you are going to need to use to represent the state of the game when played
    - [x] Decide on the tasks that will be part of the game loop
    - [ ] Write test functions for each of the tasks
    - [ ] Write functions for each of the tasks and make sure they pass your tests
  - [ ] Player vs AI
    - [ ] Decide on the data structure(s) that you are going to need to use to represent the additional state of the artificial intelligence
    - [ ] Write functions to assist with each of the tasks of the AI
    - [ ] Modify your game loop/main funciton to allow for the AI to play
    - [ ] Make sure that your AI actually does get better over time - play a few games against it. You may want to add some extra debugging output to keep an eye on the hats
- [ ] Hard Mode
  - [ ] Modify your program to allow for AI to play against AI
  - [ ] Give the human player the option to battle against the AI from normal mode or a pre-trained AI that has played a large number of simulated games
  - [ ] Examine the contents of the hats for the pre-trained AI, and see if you can determine its strategy
- [ ] Nightmare Mode
  - [ ] Write a Tic-Tac-Toe program that pre-trains its AI using the same strategy as **Hard Mode**.

**Comment by JermaineKee** [comment]
https://github.com/keezeopendoors/game-of-sticks/blob/master/sticks.py
https://github.com/keezeopendoors/game-of-sticks/blob/master/stickscomp.py
@jamesmallen 
@powder-river

**Comment by powder-river** [comment]
@keezeopendoors 
@jamesmallen 

as your checklist suggests it looks like you can play vs a human, however it's not looking like you can do anything vs. the AI. I also don't see any tests. First of all, I commend you on submitting a #shippable or MVP product. Keep in mind I am but the lower courts and James reviews all work but I am basing the label off where your code is and the fact that there were no tests attempted. In theory if you follow TDD tests are the first things that should be written. If you don't understand how to write a test let's get together tomorrow for a quick basic tutorial.

**Comment by JermaineKee** [comment]
@powder-river 
@jamesmallen 

my human vs human did run... could i at least get a yellow?

**Comment by jmaroeder** [comment]
@keezeopendoors @powder-river I updated this to yellow, as it does run and addresses at least part of the problem, but it's definitely on the cusp.

I agree with Danai that it's great you submitted a runnable program. Next time please focus on getting more of the task completed.
