### ISSUE TITLE
06--Game-of-Sticks-- Karthik Kasala

### ISSUE THREAD

**Issue by kasalak** [tiyd-python-2015-08/assigments#108]
- [x] Blank slate
  - [x] Create a GitHub repo called `game-of-sticks`
  - [x] Put a `README.md` file in it and create sticks.py and sticks_test.py.
- [ ] Normal Mode
  - [x] Player vs Player
    - [ ] Decide on the data structure(s) that you are going to need to use to represent the state of the game when played
    - [ ] Decide on the tasks that will be part of the game loop
    - [ ] Write test functions for each of the tasks
    - [ ] Write functions for each of the tasks and make sure they pass your tests
  - [ ] Player vs AI
    - [ ] Decide on the data structure(s) that you are going to need to use to represent the additional state of the artificial intelligence
    - [ ] Write functions to assist with each of the tasks of the AI
    - [ ] Modify your game loop/main funciton to allow for the AI to play
    - [ ] Make sure that your AI actually does get better over time - play a few games against it. You may want to add some extra debugging output to keep an eye on the hats
- [ ] Hard Mode
  - [ ] Modify your program to allow for AI to play against AI
  - [ ] Give the human player the option to battle against the AI from normal mode or a pre-trained AI that has played a large number of simulated games
  - [ ] Examine the contents of the hats for the pre-trained AI, and see if you can determine its strategy
- [ ] Nightmare Mode
  - [ ] Write a Tic-Tac-Toe program that pre-trains its AI using the same strategy as **Hard Mode**.

**Comment by kasalak** [comment]
@powder-river 
@jamesmallen 

https://github.com/kasalak/Game-of-Sticks
not complete

**Comment by powder-river** [comment]
@jamesmallen  @kasalak as it stands your program quits after the first time you take a stick. We should sit down today and discuss how to approach HW that does not include a boilerplate(pre-written code) It appears you got jumbled in your approach but I could be wrong
