### ISSUE TITLE
07-- Vector-Victor -- Glenn Hurley

### ISSUE THREAD

**Issue by gmhurley** [tiyd-python-2015-08/assigments#114]
- [x] Blank slate
  - [x] Create a GitHub repo called `vector-victor`
  - [x] Put a `README.md` file in it and copy linear_algebra.py and test_linear_algebra.py into it from this repository
- [x] Normal Mode (make sure you pass the tests for each of these functions)
  - [x] shape (for vectors)
  - [x] vector_add
  - [x] vector_sub
  - [x] vector_sum
  - [x] dot
  - [x] vector_multiply
  - [x] vector_mean
  - [x] magnitude
- [ ] Hard Mode (make sure you pass the tests for each of these functions)
  - [x] shape (for vectors + matrices)
  - [x] matrix_row
  - [x] matrix_col
  - [x] matrix_scalar_multiply
  - [x] matrix_vector_multiply
  - [ ] matrix_matrix_multiply

**Comment by gmhurley** [comment]
shape test passes: https://github.com/gmhurley/vector-victor/commit/fd75d523f50b459839de99b2863f168517958bc6

**Comment by gmhurley** [comment]
vector_add test passes: https://github.com/gmhurley/vector-victor/commit/827680edc07e2bb56710a0953e49b817c0bea045

**Comment by gmhurley** [comment]
vector_sub written. 6 tests passing: https://github.com/gmhurley/vector-victor/commit/61d0f4d60932696bc29079c5d4e7c1449de3bb00

**Comment by gmhurley** [comment]
vector_sub and dot written. 10 tests passing: https://github.com/gmhurley/vector-victor/commit/e2508c13d5d73ea133ab930a5abef4a2ee49e192

**Comment by gmhurley** [comment]
vector_multiply written. 11 tests passing: https://github.com/gmhurley/vector-victor/commit/8c1ca01bb54ab2c407fa84828663771edfee03c6

**Comment by gmhurley** [comment]
vector_mean written. 12 tests passing: https://github.com/gmhurley/vector-victor/commit/0cec6f6f7190563a28f9d6a14660bc258d3a82ca

**Comment by gmhurley** [comment]
magnitude written. 13 tests passing: https://github.com/gmhurley/vector-victor/commit/8b1d626192510d31ab3696024c8f0af440f9c8f2

**Comment by gmhurley** [comment]
@jamesmallen @powder-river normal mode submission:
https://github.com/gmhurley/vector-victor

**Comment by gmhurley** [comment]
wrote matrix_row(), matrix_col() and matrix_scalar_multiply(). 17 tests passing.
https://github.com/gmhurley/vector-victor/commit/51258a39fbdaf97464b192264cd466249a3b20dd

**Comment by gmhurley** [comment]
matrix_vector_multiply written. 19 tests passing.
https://github.com/gmhurley/vector-victor/commit/f3903011b75f1d233683fefabbbb795172bedfef

**Comment by powder-river** [comment]
@gmhurley hopefully this gave you the understanding of tests that you were looking for! good job glenn
