### ISSUE TITLE
07--Vector Victor-- Karthik Kasala

### ISSUE THREAD

**Issue by kasalak** [tiyd-python-2015-08/assigments#116]
- [x] Blank slate
  - [x] Create a GitHub repo called `vector-victor`
  - [x] Put a `README.md` file in it and copy linear_algebra.py and test_linear_algebra.py into it from this repository
- [x] Normal Mode (make sure you pass the tests for each of these functions)
  - [x] shape (for vectors)
  - [x] vector_add
  - [x] vector_sub
  - [x] vector_sum
  - [x] dot
  - [x] vector_multiply
  - [x] vector_mean
  - [x] magnitude
- [ ] Hard Mode (make sure you pass the tests for each of these functions)
  - [ ] shape (for vectors + matrices)
  - [ ] matrix_row
  - [ ] matrix_col
  - [ ] matrix_scalar_multiply
  - [ ] matrix_vector_multiply
  - [ ] matrix_matrix_multiply

**Comment by kasalak** [comment]
https://github.com/kasalak/Vector-Victor

@jamesmallen 
@powder-river  - Finally figured out that last shape exception!

**Comment by powder-river** [comment]
@kasalak so the grading criteria is either they all pass or they don't. if you get the last test rolling let me know.

**Comment by powder-river** [comment]
@kasalak bumped you up to green

**Comment by powder-river** [comment]
@kasalak but I'm keeping the yellow in protest because i know you just fixed it when we were going over it in class

**Comment by kasalak** [comment]
@powder-river It's okay. Black and yellow are good colors.
