### ISSUE TITLE
07 -- Vector-Victor -- Andrew Pierce

### ISSUE THREAD

**Issue by andrewmpierce** [tiyd-python-2015-08/assigments#117]
- [x] Blank slate
  - [x] Create a GitHub repo called `vector-victor`
  - [x] Put a `README.md` file in it and copy linear_algebra.py and test_linear_algebra.py into it from this repository
- [x] Normal Mode (make sure you pass the tests for each of these functions)
  - [x] shape (for vectors)
  - [x] vector_add
  - [x] vector_sub
  - [x] vector_sum
  - [x] dot
  - [x] vector_multiply
  - [x] vector_mean
  - [x] magnitude
- [ ] Hard Mode (make sure you pass the tests for each of these functions)
  - [ ] shape (for vectors + matrices)
  - [ ] matrix_row
  - [ ] matrix_col
  - [ ] matrix_scalar_multiply
  - [ ] matrix_vector_multiply
  - [ ] matrix_matrix_multiply

**Comment by andrewmpierce** [comment]
https://github.com/apierce1992/Vector-Victor/tree/master
@jamesmallen 
@powder-river

**Comment by powder-river** [comment]
@apierce1992 tests, pass, life is good, the assignment was easy as that right  :-)  good job man
