### ISSUE TITLE
07 -- Vector Victor -- Bob Amand

### ISSUE THREAD

**Issue by BobAmand** [tiyd-python-2015-08/assigments#118]
- [x] Blank slate
  - [x] Create a GitHub repo called `vector-victor`
  - [x] Put a `README.md` file in it and copy linear_algebra.py and test_linear_algebra.py into it from this repository
- [ ] Normal Mode (make sure you pass the tests for each of these functions)
  - [x] shape (for vectors)
  - [x] vector_add
  - [x] vector_sub
  - [ ] vector_sum
  - [x] dot
  - [x] vector_multiply
  - [ ] vector_mean
  - [ ] magnitude
- [ ] Hard Mode (make sure you pass the tests for each of these functions)
  - [ ] shape (for vectors + matrices)
  - [ ] matrix_row
  - [ ] matrix_col
  - [ ] matrix_scalar_multiply
  - [ ] matrix_vector_multiply
  - [ ] matrix_matrix_multiply

**Comment by BobAmand** [comment]
https://github.com/BobAmand/vector-assignment
@powder-river  @jamesmallen 
Code written for all sections of normal mode.  Only checked the functions that passed the test.

**Comment by powder-river** [comment]
@BobAmand @jamesmallen bob check your code, right now it is not running
