### ISSUE TITLE
07 -- Vector Victor -- Adam Hartz

### ISSUE THREAD

**Issue by ahartz1** [tiyd-python-2015-08/assigments#119]
- [x] Blank slate
  - [x] Create a GitHub repo called `vector-victor`
  - [x] Put a `README.md` file in it and copy linear_algebra.py and test_linear_algebra.py into it from this repository
- [x] Normal Mode (make sure you pass the tests for each of these functions)
  - [x] shape (for vectors)
  - [x] vector_add
  - [x] vector_sub
  - [x] vector_sum
  - [x] dot
  - [x] vector_multiply
  - [x] vector_mean
  - [x] magnitude
- [ ] Hard Mode (make sure you pass the tests for each of these functions)
  - [x] shape (for vectors + matrices)
  - [x] matrix_row
  - [x] matrix_col
  - [x] matrix_scalar_multiply
  - [x] matrix_vector_multiply
  - [ ] matrix_matrix_multiply

**Comment by ahartz1** [comment]
SUMBIT
https://github.com/ahartz1/vector-victor
@jamesmallen @powder-river

**Comment by powder-river** [comment]
@ahartz1 looking good adam! looks like some solid code.
