### ISSUE TITLE
07--Vector Victor-- Jermaine Kee

### ISSUE THREAD

**Issue by JermaineKee** [tiyd-python-2015-08/assigments#120]
- [x] Blank slate
  - [x] Create a GitHub repo called `vector-victor`
  - [x] Put a `README.md` file in it and copy linear_algebra.py and test_linear_algebra.py into it from this repository
- [x] Normal Mode (make sure you pass the tests for each of these functions)
  - [x] shape (for vectors)
  - [x] vector_add
  - [x] vector_sub
  - [x] vector_sum
  - [x] dot
  - [x] vector_multiply
  - [ ] vector_mean
  - [ ] magnitude
- [ ] Hard Mode (make sure you pass the tests for each of these functions)
  - [ ] shape (for vectors + matrices)
  - [ ] matrix_row
  - [ ] matrix_col
  - [ ] matrix_scalar_multiply
  - [ ] matrix_vector_multiply
  - [ ] matrix_matrix_multiply

**Comment by JermaineKee** [comment]
https://github.com/keezeopendoors/vector-victor/blob/master/linear_algebra.py
@jamesmallen 
@powder-river

**Comment by powder-river** [comment]
@jamesmallen @keezeopendoors check you code, your code is not running
