### ISSUE TITLE
07 -- Vector Victor -- Jonathan Frederick

### ISSUE THREAD

**Issue by JonathanFrederick** [tiyd-python-2015-08/assigments#124]
- [x] Blank slate
  - [x] Create a GitHub repo called `vector-victor`
  - [x] Put a `README.md` file in it and copy linear_algebra.py and test_linear_algebra.py into it from this repository
- [x] Normal Mode (make sure you pass the tests for each of these functions)
  - [x] shape (for vectors)
  - [x] vector_add
  - [x] vector_sub
  - [x] vector_sum
  - [x] dot
  - [x] vector_multiply
  - [x] vector_mean
  - [x] magnitude
- [ ] Hard Mode (make sure you pass the tests for each of these functions)
  - [x] shape (for vectors + matrices)
  - [x] matrix_row
  - [x] matrix_col
  - [ ] matrix_scalar_multiply
  - [ ] matrix_vector_multiply
  - [ ] matrix_matrix_multiply

**Comment by JonathanFrederick** [comment]
https://github.com/JonathanFrederick/vector-victor

Normal Mode completed using for loops for sum and mean, may try again and/or for Hard Mode after dinner.

@jamesmallen @powder-river

**Comment by powder-river** [comment]
@JonathanFrederick pretty straight forward grading, either the tests pass or they don't hopefully you got good practice with comprehensions
