### ISSUE TITLE
07 -- vector-victor -- Will Butts

### ISSUE THREAD

**Issue by Shea-Wolfe** [tiyd-python-2015-08/assigments#125]
- [x] Blank slate
  - [x] Create a GitHub repo called `vector-victor`
  - [x] Put a `README.md` file in it and copy linear_algebra.py and test_linear_algebra.py into it from this repository
- [x] Normal Mode (make sure you pass the tests for each of these functions)
  - [x] shape (for vectors)
  - [x] vector_add
  - [x] vector_sub
  - [x] vector_sum
  - [x] dot
  - [x] vector_multiply
  - [x] vector_mean
  - [x] magnitude
- [ ] Hard Mode (make sure you pass the tests for each of these functions)
  - [ ] shape (for vectors + matrices)
  - [ ] matrix_row
  - [ ] matrix_col
  - [ ] matrix_scalar_multiply
  - [ ] matrix_vector_multiply
  - [ ] matrix_matrix_multiply

**Comment by Shea-Wolfe** [comment]
@powder-river @jamesmallen 

https://github.com/Shea-Wolfe/vectors-victor

All standard tests passing.  Had to use a for loop for sum_vectors, still want to do it without but I'm going to try a bit of hard and might come back to it.

README is en_route.

**Comment by powder-river** [comment]
@Shea-Wolfe not much to comment on, either the tests pass or they don't, good job!
