### ISSUE TITLE
08 -- What-to-Watch -- David Denney

### ISSUE THREAD

**Issue by ghost** [tiyd-python-2015-08/assigments#126]
- [x] Blank slate
  - [x] Create a GitHub repo called `what-to-watch`
  - [x] Put a `README.md` file in it and create movie_lib.py to contain your classes
- [x] Normal mode
  - [x] Decide on the data structures that you're going to use to represent the information you'll need for this project
  - [x] Create relevant classes
  - [x] Write test code for your classes
  - [x] Load movie data using `csv` module
  - [x] Write a program to recommend popular movies
  - [x] Write a function to find similar users
  - [x] Write a program to recommend highly rated movies for a user based on similar users' favorites
  - [x] Decide on an interface for making all these things accessible and write it
- [ ] Hard Mode
  - [ ] Calculate user similarity using the Pearson correlation score
  - [ ] Write functionality to find similar movies based on their reviews from users
  - [ ] Test out your program with the MovieLens 1M dataset, and write any notes about it in the README
  - [ ] Think of some other interesting functionality and implement it!

**Comment by ghost** [comment]
SUBMITTED

@jamesmallen 
@powder-river 

https://github.com/ddenney/what-to-watch

**Comment by powder-river** [comment]
@jamesmallen @ddenney I'll admit I am perplexed as to what's going on. It looks like you put all of your code into a single class called data, however I don't see 
- an interface where you can access the data and
- I don't see where you actually read in the data anywhere in your code
  I'm not sure if this was a misunderstanding or if something went wrong in a push somewhere.
