### ISSUE TITLE
08 -- What-To-Watch -- Bob Amand

### ISSUE THREAD

**Issue by BobAmand** [tiyd-python-2015-08/assigments#128]
- [x] Blank slate
  - [x] Create a GitHub repo called `what-to-watch`
  - [x] Put a `README.md` file in it and create movie_lib.py to contain your classes
- [ ] Normal mode
  - [x] Decide on the data structures that you're going to use to represent the information you'll need for this project
  - [x] Create relevant classes
  - [x] Write test code for your classes
  - [x] Load movie data using `csv` module
  - [ ] Write a program to recommend popular movies
  - [ ] Write a function to find similar users
  - [ ] Write a program to recommend highly rated movies for a user based on similar users' favorites
  - [ ] Decide on an interface for making all these things accessible and write it
- [ ] Hard Mode
  - [ ] Calculate user similarity using the Pearson correlation score
  - [ ] Write functionality to find similar movies based on their reviews from users
  - [ ] Test out your program with the MovieLens 1M dataset, and write any notes about it in the README
  - [ ] Think of some other interesting functionality and implement it!

**Comment by BobAmand** [comment]
https://github.com/BobAmand/what-to-watch
@powder-river  @jamesmallen 
I need to learn how to learn faster.

**Comment by powder-river** [comment]
@BobAmand @jamesmallen  it looks like you have a lot of components in place but you have no interface to return any of  the data. we should sit down and discuss naming again as well. I think it will help you understand your code better.

**Comment by BobAmand** [comment]
That would be great.  I would like to re-submit this after fully reviewing the in class homework review as well.   I will come find you after class today.

Robert E. Amand
Biotherapeutic Modeling Group, Inc.
(919) 244-1487 cell
(919) 465-9584 land
biotmg@nc.rr.com
