### ISSUE TITLE
08 -- What to Watch -- Adam Hartz

### ISSUE THREAD

**Issue by ahartz1** [tiyd-python-2015-08/assigments#130]
- [x] Blank slate
  - [x] Create a GitHub repo called `what-to-watch`
  - [x] Put a `README.md` file in it and create movie_lib.py to contain your classes
- [x] Normal mode
  - [x] Decide on the data structures that you're going to use to represent the information you'll need for this project
  - [x] Create relevant classes
  - [x] Write test code for your classes
  - [x] Load movie data using `csv` module
  - [x] Write a program to recommend popular movies
  - [x] Write a function to find similar users
  - [x] Write a program to recommend highly rated movies for a user based on similar users' favorites
  - [x] Decide on an interface for making all these things accessible and write it
- [ ] Hard Mode
  - [ ] Calculate user similarity using the Pearson correlation score
  - [ ] Write functionality to find similar movies based on their reviews from users
  - [ ] Test out your program with the MovieLens 1M dataset, and write any notes about it in the README
  - [ ] Think of some other interesting functionality and implement it!

**Comment by ahartz1** [comment]
SUBMIT Normal Mode
https://github.com/ahartz1/what-to-watch
@jamesmallen @powder-river

**Comment by powder-river** [comment]
@ahartz1 I can always count on you for a really cool UI. Now on to business. I commend you on a job well done. It appears everything works well and all the calculations are correct. WOW 500 lines of code. get's kinda messy huh? I'm sure from here on out we'll be working with a class per file. That should help the workflow. Also I see you saw that TDD is the first thing to go out the window when working on tough projects. It's tough isn't it? Really good job Adam. I can tell you did a lot of work on this one.
