### ISSUE TITLE
08 -- What-To-Watch -- Glenn Hurley

### ISSUE THREAD

**Issue by gmhurley** [tiyd-python-2015-08/assigments#131]
- [x] Blank slate
  - [x] Create a GitHub repo called `what-to-watch`
  - [x] Put a `README.md` file in it and create movie_lib.py to contain your classes
- [x] Normal mode
  - [x] Decide on the data structures that you're going to use to represent the information you'll need for this project
  - [x] Create relevant classes
  - [x] Write test code for your classes
  - [x] Load movie data using `csv` module
  - [x] Write a program to recommend popular movies
  - [x] Write a function to find similar users
  - [x] Write a program to recommend highly rated movies for a user based on similar users' favorites
  - [x] Decide on an interface for making all these things accessible and write it
- [ ] Hard Mode
  - [ ] Calculate user similarity using the Pearson correlation score
  - [ ] Write functionality to find similar movies based on their reviews from users
  - [ ] Test out your program with the MovieLens 1M dataset, and write any notes about it in the README
  - [ ] Think of some other interesting functionality and implement it!

**Comment by gmhurley** [comment]
movie_by_id method in Movie class. 4 Tests passing.
https://github.com/gmhurley/what-to-watch/commit/576ef4af73b3497ab56073d025b4d4a1f45a97f4

**Comment by gmhurley** [comment]
Should have step 1 and 2 complete.
https://github.com/gmhurley/what-to-watch/commit/2ad2a1a343182b70832557c034334766bfe1ff38

**Comment by gmhurley** [comment]
Calling it a night. Top x for movies not watched by user complete:
https://github.com/gmhurley/what-to-watch/commit/073e9a1e9c3df1a3d795363075db23d3fa3ea744

**Comment by gmhurley** [comment]
Should have everything I need for interface ready to go. Tests still need some more work.
https://github.com/gmhurley/what-to-watch/tree/normal

**Comment by gmhurley** [comment]
https://github.com/gmhurley/what-to-watch

**Comment by powder-river** [comment]
@gmhurley glenn everything looks good. code runs good, no errors. but dude, TDD....
let's see more of that going forward
