### ISSUE TITLE
08 -- What to Watch -- Andrew Pierce

### ISSUE THREAD

**Issue by andrewmpierce** [tiyd-python-2015-08/assigments#132]
- [x] Blank slate
  - [x] Create a GitHub repo called `what-to-watch`
  - [x] Put a `README.md` file in it and create movie_lib.py to contain your classes
- [x] Normal mode
  - [x] Decide on the data structures that you're going to use to represent the information you'll need for this project
  - [x] Create relevant classes
  - [x] Write test code for your classes
  - [x] Load movie data using `csv` module
  - [x] Write a program to recommend popular movies
  - [x] Write a function to find similar users
  - [x] Write a program to recommend highly rated movies for a user based on similar users' favorites
  - [x] Decide on an interface for making all these things accessible and write it
- [ ] Hard Mode
  - [ ] Calculate user similarity using the Pearson correlation score
  - [ ] Write functionality to find similar movies based on their reviews from users
  - [ ] Test out your program with the MovieLens 1M dataset, and write any notes about it in the README
  - [ ] Think of some other interesting functionality and implement it!

**Comment by andrewmpierce** [comment]
@jamesmallen 
@powder-river 
Submitted 
https://github.com/andrewmpierce/what-to-watch

I went about this a different way after getting pretty stuck on Saturday night. The program provides all the required functionality but probably doesn't use the class structure as efficiently as other solutions. I am looking forward to seeing James' solution tomorrow. That being said, it works! It has a test suite, provides lots of cool data, and was still fun to make.

It's in the readme, but you want to run what_to_watch.py to get the correct interface.

**Comment by powder-river** [comment]
@andrewmpierce the code looks lean andrew I like it! It looks like options 1 and 2 work fine, check out option 3 because it's not running on my end. It looks like everything else that is running works great!
