### ISSUE TITLE
08--What-To-Watch--Karthik Kasala

### ISSUE THREAD

**Issue by kasalak** [tiyd-python-2015-08/assigments#137]
- [x] Blank slate
  - [x] Create a GitHub repo called `what-to-watch`
  - [x] Put a `README.md` file in it and create movie_lib.py to contain your classes
- [ ] Normal mode
  - [x] Decide on the data structures that you're going to use to represent the information you'll need for this project
  - [x] Create relevant classes
  - [x] Write test code for your classes
  - [x] Load movie data using `csv` module
  - [ ] Write a program to recommend popular movies
  - [ ] Write a function to find similar users
  - [ ] Write a program to recommend highly rated movies for a user based on similar users' favorites
  - [ ] Decide on an interface for making all these things accessible and write it
- [ ] Hard Mode
  - [ ] Calculate user similarity using the Pearson correlation score
  - [ ] Write functionality to find similar movies based on their reviews from users
  - [ ] Test out your program with the MovieLens 1M dataset, and write any notes about it in the README
  - [ ] Think of some other interesting functionality and implement it!

**Comment by kasalak** [comment]
https://github.com/kasalak/what-to-watch

**Comment by powder-river** [comment]
@kasalak @jamesmallen as we just talked there is no way to actually run the program. see if you can get a UI up and rolling and we can re evaluate
