### ISSUE TITLE
08 -- what-to-watch -- Will Butts

### ISSUE THREAD

**Issue by Shea-Wolfe** [tiyd-python-2015-08/assigments#138]
- [x] Blank slate
  - [x] Create a GitHub repo called `what-to-watch`
  - [x] Put a `README.md` file in it and create movie_lib.py to contain your classes
- [x] Normal mode
  - [x] Decide on the data structures that you're going to use to represent the information you'll need for this project
  - [x] Create relevant classes
  - [x] Write test code for your classes
  - [x] Load movie data using `csv` module
  - [x] Write a program to recommend popular movies
  - [x] Write a function to find similar users
  - [x] Write a program to recommend highly rated movies for a user based on similar users' favorites
  - [x] Decide on an interface for making all these things accessible and write it
- [ ] Hard Mode
  - [ ] Calculate user similarity using the Pearson correlation score
  - [ ] Write functionality to find similar movies based on their reviews from users
  - [ ] Test out your program with the MovieLens 1M dataset, and write any notes about it in the README
  - [ ] Think of some other interesting functionality and implement it!

**Comment by Shea-Wolfe** [comment]
@jamesmallen @powder-river 

https://github.com/Shea-Wolfe/what-to-watch

I wanted to get something up.  I wasn't sure how to test methods so I just commented out the classes and tested them as functions.  My README needs to be updated but I will do so this weekend.

Update:  I thought about it and remembered how classes worked.  Now test suite is working with classes and everything.  Time for bed.

**Comment by Shea-Wolfe** [comment]
@jamesmallen @powder-river 

Program has been updated with key functionality.  Currently my function to get a recommendation from a similar user only suggests a highly reviewed movie that the similar user has seen but the current user hasn't, it doesn't take the similar users actual rating into account.

My readme needs to be updated (badly) and I need to add to my testing suite and ensure my code isn't terribly venerable to bad input.  I will likely be focusing on that tomorrow (Sunday).

**Comment by Shea-Wolfe** [comment]
@jamesmallen @powder-river 

Ok, did some more work with my program.  Realized I could store multiple similar users by setting a minimum similarity rather than only keeping the most similar.  Used that to pick movies each of those users liked and taking the rating of that movie (from all ratings) multiplied by their euclidean distance (since if I did their personal rating it would probably always be a 5, thus the most similar would always be returned).  I think this satisfies the requirement to get similar users and use the distance from them to help decide what to watch.

Readme is a few hours out of date but the run instructions still work.

https://github.com/Shea-Wolfe/what-to-watch

**Comment by powder-river** [comment]
@Shea-Wolfe looking good will, I mean we could talk some UI things to make to a little more clear what's going on but all and all strong submit. It doesn't look like you tested "every" method, however it looks like you tested quite a bit.  Good submit will
