### ISSUE TITLE
08 -- What-to-Watch -- Jonathan Frederick

### ISSUE THREAD

**Issue by JonathanFrederick** [tiyd-python-2015-08/assigments#139]
- [x] Blank slate
  - [x] Create a GitHub repo called `what-to-watch`
  - [x] Put a `README.md` file in it and create movie_lib.py to contain your classes
- [x] Normal mode
  - [x] Decide on the data structures that you're going to use to represent the information you'll need for this project
  - [x] Create relevant classes
  - [x] Write test code for your classes
  - [x] Load movie data using `csv` module
  - [x] Write a program to recommend popular movies
  - [x] Write a function to find similar users
  - [x] Write a program to recommend highly rated movies for a user based on similar users' favorites
  - [x] Decide on an interface for making all these things accessible and write it
- [ ] Hard Mode
  - [ ] Calculate user similarity using the Pearson correlation score
  - [ ] Write functionality to find similar movies based on their reviews from users
  - [ ] Test out your program with the MovieLens 1M dataset, and write any notes about it in the README
  - [ ] Think of some other interesting functionality and implement it!

**Comment by JonathanFrederick** [comment]
https://github.com/JonathanFrederick/what-to-watch

**Comment by JonathanFrederick** [comment]
@jamesmallen @powder-river 
MVP is there, still plenty of tweaking I can do

**Comment by powder-river** [comment]
@JonathanFrederick  good submit john, like you said MVP is defiantly there. Missing a couple things here and there but that's a hell of a strong MVP Jon. I know you missed out on friday, let us know what we can do to help if you have questions. good job!
