### ISSUE TITLE
09 -- Modern-Art -- David Denney

### ISSUE THREAD

**Issue by ghost** [tiyd-python-2015-08/assigments#140]
- [x] Blank slate
  - [x] Create a GitHub repo called `modern-art`
  - [x] Put a `README.md` file in it
  - [x] Copy `requirements.txt`, `create_art.py`, and `random_art.py` into it frmo this repo
  - [x] Make sure your modern-art folder has its own virtual environment (`.envrc`), but **do not commit `.envrc` or `.direnv`**
  - [x] Install the requirements using `pip install -r requirements.txt`
- [x] Normal mode
  - [x] Test create_art.py and random_art.py, and examine random_art.py to determine how art is randomly being created
  - [x] Modify the create_expression function in random_art.py and come up with your own algorithm for generating random art
  - [x] Run create_art.py with your new function(s) and find some awesome artwork
  - [x] Commit at least one created artwork you particularly like, and include instructions in your `README.md` file for how to reproduce it
- [ ] Hard Mode
  - [ ] Implement an [abstract syntax tree][] or some other algorithm that requires modifying run_expression to work with

**Comment by ghost** [comment]
SUBMITTED

@jamesmallen 
@powder-river 

https://github.com/ddenney/modern-art

**Comment by powder-river** [comment]
@ddenney it looks like you have pictures there, but your code doesn't run.

**Comment by ghost** [comment]
@powder-river that's strange it's working on my end. What happens when you run: python create_art.py -S 237786807060663633

Also, running python create_art.py seems to be working for me as well.
