### ISSUE TITLE
10 -- Flipping-Out -- Glenn Hurley

### ISSUE THREAD

**Issue by gmhurley** [tiyd-python-2015-08/assigments#155]
- [x] Blank slate
  - [x] Create a GitHub repo called `flipping-out`
  - [x] Put `README.md` and `requirements.txt` files in it
  - [x] Make sure ipython[all] and any necessary plotting libraries are in `requirements.txt`
  - [x] Make sure your flipping-out folder has its own virtual environment (`.envrc`), but **do not commit `.envrc` or `.direnv`**
  - [x] Install the requirements using `pip install -r requirements.txt`
- [ ] Normal mode
  - [x] Create an IPython Notebook file called `coin-flips.ipynb`
  - [x] Create a function to flip a coin
  - [x] Create a function to simulate flipping a coin _n_ times, recording how many heads and tails it has seen at exponential intervals (2<sup>0</sup>, 2<sup>1</sup>, 2<sup>2</sup>..._n_)
    - [x] Make a line plot of the **difference** between heads and tails at each point
    - [x] Make a line plot of the **ratio** of heads to tails at each point
    - [x] Create the above two plots as scatter plots with a logarithmic scale for the x-axis
    - [x] Write notes about your observations and add other plots as necessary
  - [ ] Create a function that uses your above simulation function, but runs 20 trials where _n_ = 2<sup>16</sup>
    - [ ] Create a scatter plot of the mean heads/tails ratio at each recorded point
    - [ ] Create a scatter plot of the standard deviation of the heads/tails ratio at each recorded point
    - [ ] Use a logarithmic scale for the x-axis with both of the above plots, and a logarithmic scale for the y-axis for the standard deviation plot
  - [ ] Create a function to run 100,000 trials of 100 flips per trial
    - [ ] Plot a histogram of the ratio of heads to total flips for each trial.
    - [ ] Plot a box plot of the same results
  - [ ] Create a function to run 100,000 trials of 1,000 flips per trial
    - [ ] Plot a histogram of the ratio of heads to total flips for each trial.
    - [ ] Plot a box plot of the same results
    - [ ] Compare the 1,000 flips per trial results to the 100 flips per trial results
- [ ] Hard Mode
  - [ ] Use seaborn and clean up your Notebook file for presentation

**Comment by gmhurley** [comment]
@jamesmallen @powder-river 
Need to put a pin in it for the night. Going to need to get some sleep so I can absorb all this in the morning.
https://github.com/gmhurley/flipping-out

**Comment by powder-river** [comment]
@gmhurley I could tell yesterday that you just LOVE working with math and graphs ;-)  It's not a bad submission glenn. You're obviously on the right path with everything. I'm sure HW review today will answer any questions you have.

**Comment by gmhurley** [comment]
@powder-river So I don't feel like I had any problem with Python last night, I feel like I struggled with understanding the requirements. Would it be possible to step through the requirements with either you or @jamesmallen this afternoon? I'd like to make sure I understand what we were trying to accomplish.
