### ISSUE TITLE
10 -- Flipping Out -- Bob Amand

### ISSUE THREAD

**Issue by BobAmand** [tiyd-python-2015-08/assigments#156]
- [x] Blank slate
  - [x] Create a GitHub repo called `flipping-out`
  - [x] Put `README.md` and `requirements.txt` files in it
  - [x] Make sure ipython[all] and any necessary plotting libraries are in `requirements.txt`
  - [x] Make sure your flipping-out folder has its own virtual environment (`.envrc`), but **do not commit `.envrc` or `.direnv`**
  - [x] Install the requirements using `pip install -r requirements.txt`
- [ ] Normal mode
  - [x] Create an IPython Notebook file called `coin-flips.ipynb`
  - [x] Create a function to flip a coin
  - [x] Create a function to simulate flipping a coin _n_ times, recording how many heads and tails it has seen at exponential intervals (2<sup>0</sup>, 2<sup>1</sup>, 2<sup>2</sup>..._n_)
    - [x] Make a line plot of the **difference** between heads and tails at each point
    - [x] Make a line plot of the **ratio** of heads to tails at each point
    - [x] Create the above two plots as scatter plots with a logarithmic scale for the x-axis
    - [x] Write notes about your observations and add other plots as necessary
  - [ ] Create a function that uses your above simulation function, but runs 20 trials where _n_ = 2<sup>16</sup>
    - [ ] Create a scatter plot of the mean heads/tails ratio at each recorded point
    - [ ] Create a scatter plot of the standard deviation of the heads/tails ratio at each recorded point
    - [ ] Use a logarithmic scale for the x-axis with both of the above plots, and a logarithmic scale for the y-axis for the standard deviation plot
  - [ ] Create a function to run 100,000 trials of 100 flips per trial
    - [ ] Plot a histogram of the ratio of heads to total flips for each trial.
    - [ ] Plot a box plot of the same results
  - [ ] Create a function to run 100,000 trials of 1,000 flips per trial
    - [ ] Plot a histogram of the ratio of heads to total flips for each trial.
    - [ ] Plot a box plot of the same results
    - [ ] Compare the 1,000 flips per trial results to the 100 flips per trial results
- [ ] Hard Mode
  - [ ] Use seaborn and clean up your Notebook file for presentation

**Comment by BobAmand** [comment]
https://github.com/BobAmand/flipping-out
@powder-river  @jamesmallen 
Could not get past consolidating the 20 trials over the initial function.

**Comment by powder-river** [comment]
@BobAmand first off, good job getting an MVP out. That's what i'm talking about. Looks like you got a decent bit done so I commend you on that. Some comments:
- the code is a little"messy". things like keep all your imports together, keep variables together etc.
- in this case its probably a little cleaner to pass in a number directly to your function, just a thought
- i am unsure about the math. You're graphs look a little weird to me but I'll defer to @jamesmallen to make that call. I suspect either some math is a little off or your TA is an idiot and doesn't know math

again I want to reiterate that this is a good MVP Bob. Keep up that mentality.
