### ISSUE TITLE
01 -- Fly Your Flag -- David Denney

### ISSUE THREAD

**Issue by ghost** [tiyd-python-2015-08/assigments#16]
- [x] Code It
  - [x] Draw a flag with one or more turtles
- [x] Press the Issue
  - [x] Open a _WIP issue_ named `01 -- Fly Your Flag -- YOUR NAME`
  - [x] Put this task list in the description
  - [x] Check off the boxes as you complete items
  - [x] Add a comment with the _Share_ link to your flag
- [ ] Hard Mode (optional)
  - [ ] Move flag drawing code to a function
  - [ ] Add a paramter to the function called size
  - [ ] Test your flag drawing at various sizes to ensure it works

**Comment by ghost** [comment]
https://trinket.io/python/2bd1dfaa62

**Comment by ghost** [comment]
SUBMITTED 

@jamesmallen @powder-river

**Comment by jmaroeder** [comment]
Looks good!
