### ISSUE TITLE
01 -- Fly Your Flag -- GLENN HURLEY

### ISSUE THREAD

**Issue by gmhurley** [tiyd-python-2015-08/assigments#17]
- [x] Code It
  - [x] Draw a flag with one or more turtles
- [x] Press the Issue
  - [x] Open a _WIP issue_ named `01 -- Fly Your Flag -- YOUR NAME`
  - [x] Put this task list in the description
  - [x] Check off the boxes as you complete items
  - [x] Add a comment with the _Share_ link to your flag
- [x] Hard Mode (optional)
  - [x] Move flag drawing code to a function
  - [x] Add a paramter to the function called size
  - [x] Test your flag drawing at various sizes to ensure it works

**Comment by gmhurley** [comment]
SUBMIT @jamesmallen @powder-river 
https://gist.github.com/gmhurley/0ffc95379ab2c4baa0b3

Not sure where we were supposed to paste the code. Let me know if it needs to be somewhere else.

**Comment by powder-river** [comment]
@gmhurley looking good, we talked about how you could change your code to take user input before you left so we are all good!
