### ISSUE TITLE
11 -- Ultimate Pig -- Bob Amand

### ISSUE THREAD

**Issue by BobAmand** [tiyd-python-2015-08/assigments#174]
- [x] Blank slate
  - [x] Create a GitHub repo called `ultimate-pig`
  - [x] Put `README.md` and `requirements.txt` files in it
  - [x] Make sure ipython[all] and any necessary plotting libraries are in `requirements.txt`
  - [x] Make sure your `ultimate-pig` folder has its own virtual environment (`.envrc`), but **do not commit `.envrc` or `.direnv`**
  - [x] Install the requirements using `pip install -r requirements.txt`
- [x] Normal mode
  - [x] Create an IPython Notebook file for simulating the game
  - [x] Create a class for keeping track of the game state
  - [x] Create a `Player` base class for a Pig player
  - [x] Create at least two subclasses of `Player` that use two different strategies for playing the game
  - [x] Run a large number of trials of the game with each subclass of `Player`
  - [x] Plot the results of your players
  - [x] Attempt to improve upon your best strategy, and use charts and data to determine if your new player is better
- [ ] Hard Mode
  - [ ] Create a simulation of a 2-player game of Pig
  - [ ] Create a new Player class for the 2-player version, and try pitting it against your optimal Pig Solitaire player
  - [ ] Create charts and data analyzing the 2 players' performance over a large number of trials

**Comment by BobAmand** [comment]
https://github.com/BobAmand/ultimate-pig
@powder-river  @jamesmallen 
Two IPython versions.  
1. class buildout did not reach simulation level functionality (ultimate-pig)
2. was able to simulate multiple scenarios using primitive programming (simple-ultimate-pig)

**Comment by powder-river** [comment]
@BobAmand good work and good discussion this morning. Like we talked about today really soak in classes during lecture today, they aren't going away. Embrace them!!! Like I said you've been upping your game. Keep asking questions,keep working hard!
