### ISSUE TITLE
11--Ultimate Pig--Jermaine Kee

### ISSUE THREAD

**Issue by JermaineKee** [tiyd-python-2015-08/assigments#177]
- [x] Blank slate
  - [x] Create a GitHub repo called `ultimate-pig`
  - [x] Put `README.md` and `requirements.txt` files in it
  - [x] Make sure ipython[all] and any necessary plotting libraries are in `requirements.txt`
  - [x] Make sure your `ultimate-pig` folder has its own virtual environment (`.envrc`), but **do not commit `.envrc` or `.direnv`**
  - [x] Install the requirements using `pip install -r requirements.txt`
- [x] Normal mode
  - [x] Create an IPython Notebook file for simulating the game
  - [x] Create a class for keeping track of the game state
  - [x] Create a `Player` base class for a Pig player
  - [x] Create at least two subclasses of `Player` that use two different strategies for playing the game
  - [x] Run a large number of trials of the game with each subclass of `Player`
  - [x] Plot the results of your players
  - [ ] Attempt to improve upon your best strategy, and use charts and data to determine if your new player is better
- [ ] Hard Mode
  - [ ] Create a simulation of a 2-player game of Pig
  - [ ] Create a new Player class for the 2-player version, and try pitting it against your optimal Pig Solitaire player
  - [ ] Create charts and data analyzing the 2 players' performance over a large number of trials

**Comment by JermaineKee** [comment]
https://github.com/keezeopendoors/ultimate-pig

@jamesmallen 
@powder-river

**Comment by powder-river** [comment]
@keezeopendoors good submit jermaine, the only thing I'm going to say is don't be afraid to get away from the boiler plate and try new methods. So you ran two simulations, after that go ahead and implement a new strategy and see if you can improve the better of the two strategies.

**Comment by JermaineKee** [comment]
https://github.com/keezeopendoors/ultimate-pig

attempt at some optimizing

@powder-river 
@jamesmallen

**Comment by powder-river** [comment]
@keezeopendoors that looks better. good job!
