### ISSUE TITLE
12 -- Road Rage -- Adam Hartz

### ISSUE THREAD

**Issue by ahartz1** [tiyd-python-2015-08/assigments#179]
- [x] Blank slate
  - [x] Create a GitHub repo called `road-rage`
  - [x] Put `README.md` and `requirements.txt` files in it
  - [x] Make sure `ipython[all]`, `numpy`, and any necessary plotting libraries are in `requirements.txt`
  - [x] Make sure your `road-rage` folder has its own virtual environment (`.envrc`), but **do not commit `.envrc` or `.direnv`**
  - [x] Install the requirements using `pip install -r requirements.txt`
- [x] Normal mode
  - [x] Create a module for the class or functions you are going to use for your simulation
  - [x] Create an IPython notebook file for gathering your data
  - [x] Import your module into your IPython notebook and gather/plot data inside of the notebook

**Comment by ahartz1** [comment]
SUBMIT Normal Mode (in master branch)
https://github.com/ahartz1/road-rage
@jamesmallen @powder-river

**Comment by ahartz1** [comment]
I have a Hard Mode in the hard_mode branch. Judging from the graphs, something doesn't smell right. I also gave an initial stab at nightmare in the nightmare_mode branch, but it is too late for me to think straight.

**Comment by powder-river** [comment]
@ahartz1 great looking data adam!  your classes look good and the data seems reasonable
