### ISSUE TITLE
01 -- Fly Your Flag -- Michael Krawiec

### ISSUE THREAD

**Issue by msk007** [tiyd-python-2015-08/assigments#18]
- [x] Code It
  - [x] Draw a flag with one or more turtles
- [x] Press the Issue
  - [x] Open a _WIP issue_ named `01 -- Fly Your Flag -- YOUR NAME`
  - [x] Put this task list in the description
  - [x] Check off the boxes as you complete items
  - [x] Add a comment with the _Share_ link to your flag
- [ ] Hard Mode (optional)
  - [ ] Move flag drawing code to a function
  - [ ] Add a paramter to the function called size
  - [ ] Test your flag drawing at various sizes to ensure it works

**Comment by msk007** [comment]
ugh. I,ve been at this for two hours and got a Polish Flag. wasn't able to hang around today due to kids transportation situation from school and i definitely feel like i missed out . I feel like with some help, i could do a lot more with this.I plan on revisiting the topic later. see you guys in 8 hrs.

https://trinket.io/python/94b1b1a492

SUBMIT
@jamesmallen 
@powder-river

**Comment by msk007** [comment]
updated

**Comment by jmaroeder** [comment]
Life happens. What you've submitted meets the requirements, and sometimes that's all you need to worry about. Hopefully you'll get more opportunities to dig a little deeper over the next 12 weeks , but for now, don't sweat it!
