### ISSUE TITLE
12 -- Road-Rage -- David Denney

### ISSUE THREAD

**Issue by ghost** [tiyd-python-2015-08/assigments#180]
- [x] Blank slate
  - [x] Create a GitHub repo called `road-rage`
  - [x] Put `README.md` and `requirements.txt` files in it
  - [x] Make sure `ipython[all]`, `numpy`, and any necessary plotting libraries are in `requirements.txt`
  - [x] Make sure your `road-rage` folder has its own virtual environment (`.envrc`), but **do not commit `.envrc` or `.direnv`**
  - [x] Install the requirements using `pip install -r requirements.txt`
- [x] Normal mode
  - [x] Create a module for the class or functions you are going to use for your simulation
  - [x] Create an IPython notebook file for gathering your data
  - [x] Import your module into your IPython notebook and gather/plot data inside of the notebook

**Comment by ddenney** [comment]
* [ ] Blank slate
  * [ ] Create a GitHub repo called `road-rage`
  * [ ] Put `README.md` and `requirements.txt` files in it
  * [ ] Make sure `ipython[all]`, `numpy`, and any necessary plotting libraries are in `requirements.txt`
  * [ ] Make sure your `road-rage` folder has its own virtual environment (`.envrc`), but **do not commit `.envrc` or `.direnv`**
  * [ ] Install the requirements using `pip install -r requirements.txt`
* [ ] Normal mode
  * [ ] Create a module for the class or functions you are going to use for your simulation
  * [ ] Create an IPython notebook file for gathering your data
  * [ ] Import your module into your IPython notebook and gather/plot data inside of the notebook

**Comment by ghost** [comment]
SUBMITTED

@jamesmallen 
@powder-river 

https://github.com/ddenney/road-rage
