### ISSUE TITLE
12 -- Road Rage -- Karthik Kasala

### ISSUE THREAD

**Issue by kasalak** [tiyd-python-2015-08/assigments#181]
- [x] Blank slate
  - [x] Create a GitHub repo called `road-rage`
  - [x] Put `README.md` and `requirements.txt` files in it
  - [x] Make sure `ipython[all]`, `numpy`, and any necessary plotting libraries are in `requirements.txt`
  - [x] Make sure your `road-rage` folder has its own virtual environment (`.envrc`), but **do not commit `.envrc` or `.direnv`**
  - [x] Install the requirements using `pip install -r requirements.txt`
- [ ] Normal mode
  - [ ] Create a module for the class or functions you are going to use for your simulation
  - [x] Create an IPython notebook file for gathering your data
  - [ ] Import your module into your IPython notebook and gather/plot data inside of the notebook

**Comment by kasalak** [comment]
https://github.com/kasalak/Road-Rage

**Comment by powder-river** [comment]
@kasalak @jamesmallen  come find one of us today and let's talk about your code
