### ISSUE TITLE
12 -- Road Rage -- Andrew Pierce

### ISSUE THREAD

**Issue by andrewmpierce** [tiyd-python-2015-08/assigments#185]
- [x] Blank slate
  - [x] Create a GitHub repo called `road-rage`
  - [x] Put `README.md` and `requirements.txt` files in it
  - [x] Make sure `ipython[all]`, `numpy`, and any necessary plotting libraries are in `requirements.txt`
  - [x] Make sure your `road-rage` folder has its own virtual environment (`.envrc`), but **do not commit `.envrc` or `.direnv`**
  - [x] Install the requirements using `pip install -r requirements.txt`
- [x] Normal mode
  - [x] Create a module for the class or functions you are going to use for your simulation
  - [x] Create an IPython notebook file for gathering your data
  - [x] Import your module into your IPython notebook and gather/plot data inside of the notebook

**Comment by andrewmpierce** [comment]
@powder-river 
Submitted Normal Mode!
I have some pretty (and informative!) graphs and make suggestions on a speed limit based on the data received.  

https://github.com/andrewmpierce/Road-Rage

**Comment by powder-river** [comment]
@andrewmpierce good job andrew! as you saw in class you now know how you can change the ratio to make your traffic graphs easier to read
