### ISSUE TITLE
12 -- Road Rage -- Glenn Hurley

### ISSUE THREAD

**Issue by gmhurley** [tiyd-python-2015-08/assigments#187]
- [x] Blank slate
  - [x] Create a GitHub repo called `road-rage`
  - [x] Put `README.md` and `requirements.txt` files in it
  - [x] Make sure `ipython[all]`, `numpy`, and any necessary plotting libraries are in `requirements.txt`
  - [x] Make sure your `road-rage` folder has its own virtual environment (`.envrc`), but **do not commit `.envrc` or `.direnv`**
  - [x] Install the requirements using `pip install -r requirements.txt`
- [ ] Normal mode
  - [ ] Create a module for the class or functions you are going to use for your simulation
  - [x] Create an IPython notebook file for gathering your data
  - [ ] Import your module into your IPython notebook and gather/plot data inside of the notebook

**Comment by gmhurley** [comment]
I was not able to get the cars to stop running into one another.
https://github.com/gmhurley/road-rage

**Comment by powder-river** [comment]
@gmhurley right, other than this whole collision thing it looks good to me. for future ref, you don't need to print out the huge array of data.
