### ISSUE TITLE
12 -- Road Rage -- Jonathan Frederick

### ISSUE THREAD

**Issue by JonathanFrederick** [tiyd-python-2015-08/assigments#188]
- [x] Blank slate
  - [x] Create a GitHub repo called `road-rage`
  - [x] Put `README.md` and `requirements.txt` files in it
  - [x] Make sure `ipython[all]`, `numpy`, and any necessary plotting libraries are in `requirements.txt`
  - [x] Make sure your `road-rage` folder has its own virtual environment (`.envrc`), but **do not commit `.envrc` or `.direnv`**
  - [x] Install the requirements using `pip install -r requirements.txt`
- [x] Normal mode
  - [x] Create a module for the class or functions you are going to use for your simulation
  - [x] Create an IPython notebook file for gathering your data
  - [x] Import your module into your IPython notebook and gather/plot data inside of the notebook

**Comment by JonathanFrederick** [comment]
https://github.com/JonathanFrederick/road-rage

**Comment by powder-river** [comment]
@JonathanFrederick code looks solid man, as you saw in class we can adjust the ratios of our graphs to increase readability
