### ISSUE TITLE
12 -- Road Rage -- Bob Amand

### ISSUE THREAD

**Issue by BobAmand** [tiyd-python-2015-08/assigments#189]
- [x] Blank slate
  - [x] Create a GitHub repo called `road-rage`
  - [x] Put `README.md` and `requirements.txt` files in it
  - [x] Make sure `ipython[all]`, `numpy`, and any necessary plotting libraries are in `requirements.txt`
  - [x] Make sure your `road-rage` folder has its own virtual environment (`.envrc`), but **do not commit `.envrc` or `.direnv`**
  - [x] Install the requirements using `pip install -r requirements.txt`
- [x] Normal mode
  - [x] Create a module for the class or functions you are going to use for your simulation
  - [x] Create an IPython notebook file for gathering your data
  - [x] Import your module into your IPython notebook and gather/plot data inside of the notebook

**Comment by BobAmand** [comment]
https://github.com/BobAmand/road-rage
@powder-river   @jamesmallen

**Comment by powder-river** [comment]
@BobAmand @jamesmallen so we reviewed your HW together this morning. It looks like you have a better understanding of classes just wasn't able to put it all together. All in all Bob I think last week was a good week of improvement for you. Don't let this assignment get you down, keep pressing, keep asking questions.
