### ISSUE TITLE
12--Road Rage--Jermaine Kee

### ISSUE THREAD

**Issue by JermaineKee** [tiyd-python-2015-08/assigments#190]
- [x] Blank slate
  - [x] Create a GitHub repo called `road-rage`
  - [x] Put `README.md` and `requirements.txt` files in it
  - [x] Make sure `ipython[all]`, `numpy`, and any necessary plotting libraries are in `requirements.txt`
  - [x] Make sure your `road-rage` folder has its own virtual environment (`.envrc`), but **do not commit `.envrc` or `.direnv`**
  - [x] Install the requirements using `pip install -r requirements.txt`
- [ ] Normal mode
  - [x] Create a module for the class or functions you are going to use for your simulation
  - [x] Create an IPython notebook file for gathering your data
  - [ ] Import your module into your IPython notebook and gather/plot data inside of the notebook

**Comment by JermaineKee** [comment]
https://github.com/keezeopendoors/road-rage

@jamesmallen 
@powder-river

**Comment by powder-river** [comment]
@jamesmallen  @keezeopendoors It looks like you did not import your module into your python notebook. If you do not understand how to do that let's talk. 

Let's try and get together to talk about classes, there appear to be some funny things going on.
