### ISSUE TITLE
14 -- Express-Yourself -- David Denney

### ISSUE THREAD

**Issue by ghost** [tiyd-python-2015-08/assigments#206]
- [x] Blank slate
  - [x] Create a GitHub repo called `express-yourself`
  - [x] Copy all the files from this repo into it
  - [x] Set up your requirements/virtual environment
- [x] Normal mode
  - [x] Pass all the prewritten tests up to `HARD MODE BEGINS` in each test file
- [ ] Hard mode
  - [ ] Pass the rest of the tests
- [ ] Nightmare mode
  - [ ] Add validators, separators, and extractors with tests for:
    - [ ] URLs
    - [ ] Times
    - [ ] ISO 8601
    - [ ] Palindromes

**Comment by ghost** [comment]
SUBMITTED 

@jamesmallen 
@powder-river 

https://github.com/ddenney/express-yourself

All tests running successfully with the exception of the last 3 separator tests. Will continue working on this tomorrow.

**Comment by powder-river** [comment]
@ddenney good job on regex, if you decide you want to try and finish off the tests let me know, you're close!
