### ISSUE TITLE
14 -- Express Yourself -- Karthik Kasala

### ISSUE THREAD

**Issue by kasalak** [tiyd-python-2015-08/assigments#209]
- [x] Blank slate
  - [x] Create a GitHub repo called `express-yourself`
  - [x] Copy all the files from this repo into it
  - [x] Set up your requirements/virtual environment
- [ ] Normal mode
  - [ ] Pass all the prewritten tests up to `HARD MODE BEGINS` in each test file
- [ ] Hard mode
  - [ ] Pass the rest of the tests
- [ ] Nightmare mode
  - [ ] Add validators, separators, and extractors with tests for:
    - [ ] URLs
    - [ ] Times
    - [ ] ISO 8601
    - [ ] Palindromes

**Comment by kasalak** [comment]
@powder-river 
https://github.com/kasalak/Express-Yourself
couldn't get past  last two tests in separator.py

**Comment by powder-river** [comment]
@kasalak looks like you got a decent bit of tests completed. Good job! Hopefully now you have more xp with regex
