### ISSUE TITLE
14--Express Yourself--Kathleen Rauh

### ISSUE THREAD

**Issue by nckathleen** [tiyd-python-2015-08/assigments#211]
- [x] Blank slate
  - [x] Create a GitHub repo called `express-yourself`
  - [x] Copy all the files from this repo into it
  - [x] Set up your requirements/virtual environment
- [ ] Normal mode
  - [ ] Pass all the prewritten tests up to `HARD MODE BEGINS` in each test file
- [ ] Hard mode
  - [ ] Pass the rest of the tests
- [ ] Nightmare mode
  - [ ] Add validators, separators, and extractors with tests for:
    - [ ] URLs
    - [ ] Times
    - [ ] ISO 8601
    - [ ] Palindromes

**Comment by nckathleen** [comment]
https://github.com/nckathleen/Express-Yourself/tree/master/textminer
@powder-river @jamesmallen

**Comment by powder-river** [comment]
@nckathleen so it looks like py.test is throwing out errors which you indicated to me in class that it might. I know today is super busy, PLEASE feel free to reach out with screen hero tonight if you have questions that don't get answered today.
