### ISSUE TITLE
14 -- express yourself -- Will Butts

### ISSUE THREAD

**Issue by Shea-Wolfe** [tiyd-python-2015-08/assigments#212]
- [x] Blank slate
  - [x] Create a GitHub repo called `express-yourself`
  - [x] Copy all the files from this repo into it
  - [x] Set up your requirements/virtual environment
- [x] Normal mode
  - [x] Pass all the prewritten tests up to `HARD MODE BEGINS` in each test file
- [ ] Hard mode
  - [ ] Pass the rest of the tests
- [ ] Nightmare mode
  - [ ] Add validators, separators, and extractors with tests for:
    - [ ] URLs
    - [ ] Times
    - [ ] ISO 8601
    - [ ] Palindromes

**Comment by Shea-Wolfe** [comment]
@jamesmallen @powder-river 

https://github.com/Shea-Wolfe/express-yourself

All normal tests passing.  README needs to be updated.  Hoping to double back to clean up some of the code.

update: README updated.  All hard tests but address separator and hard date separator passing.

**Comment by powder-river** [comment]
@Shea-Wolfe I'm getting errors when running your code double check it and see what's going on

**Comment by powder-river** [comment]
@Shea-Wolfe good fix
