### ISSUE TITLE
14 -- Express Yourself -- Andrew Pierce

### ISSUE THREAD

**Issue by andrewmpierce** [tiyd-python-2015-08/assigments#214]
- [x] Blank slate
  - [x] Create a GitHub repo called `express-yourself`
  - [x] Copy all the files from this repo into it
  - [x] Set up your requirements/virtual environment
- [x] Normal mode
  - [x] Pass all the prewritten tests up to `HARD MODE BEGINS` in each test file
- [ ] Hard mode
  - [ ] Pass the rest of the tests
- [ ] Nightmare mode
  - [ ] Add validators, separators, and extractors with tests for:
    - [ ] URLs
    - [ ] Times
    - [ ] ISO 8601
    - [ ] Palindromes

**Comment by andrewmpierce** [comment]
https://github.com/andrewmpierce/Express-Yourself
@powder-river 
All the normal mode tests passing.

**Comment by powder-river** [comment]
@andrewmpierce DAAAAAAANNNNNNNGGGG! Clean sweep andrew, awesome job with regex!
