### ISSUE TITLE
14 -- Express Yourself -- Adam Hartz

### ISSUE THREAD

**Issue by ahartz1** [tiyd-python-2015-08/assigments#215]
- [x] Blank slate
  - [x] Create a GitHub repo called `express-yourself`
  - [x] Copy all the files from this repo into it
  - [x] Set up your requirements/virtual environment
- [x] Normal mode
  - [x] Pass all the prewritten tests up to `HARD MODE BEGINS` in each test file
- [ ] Hard mode
  - [ ] Pass the rest of the tests
- [ ] Nightmare mode
  - [ ] Add validators, separators, and extractors with tests for:
    - [ ] URLs
    - [ ] Times
    - [ ] ISO 8601
    - [ ] Palindromes

**Comment by ahartz1** [comment]
SUBMIT
https://github.com/ahartz1/express-yourself
@jamesmallen @powder-river

**Comment by powder-river** [comment]
@ahartz1 my man..., 'nuff said. Great code! You took Regex to the woodshed. Keep up the awesome progress!
