### ISSUE TITLE
14 -- Express-Yourself -- Glenn Hurley

### ISSUE THREAD

**Issue by gmhurley** [tiyd-python-2015-08/assigments#216]
- [x] Blank slate
  - [x] Create a GitHub repo called `express-yourself`
  - [x] Copy all the files from this repo into it
  - [x] Set up your requirements/virtual environment
- [ ] Normal mode
  - [ ] Pass all the prewritten tests up to `HARD MODE BEGINS` in each test file
- [ ] Hard mode
  - [ ] Pass the rest of the tests
- [ ] Nightmare mode
  - [ ] Add validators, separators, and extractors with tests for:
    - [ ] URLs
    - [ ] Times
    - [ ] ISO 8601
    - [ ] Palindromes

**Comment by gmhurley** [comment]
@powder-river @jamesmallen 
ran out of time... think I made this a lot harder on myself than I had to. Looking forward to tomorrow's review.
https://github.com/gmhurley/express-yourself

**Comment by powder-river** [comment]
@gmhurley hey not bad glenn. I get that regex is a different beast. Like james said they are very powerful but they get extremely complex very quick!
