### ISSUE TITLE
15 -- moneyball -- Will Butts

### ISSUE THREAD

**Issue by Shea-Wolfe** [tiyd-python-2015-08/assigments#218]
- [x] Blank slate
  - [x] Create a GitHub repo called `moneyball`
  - [x] Copy all the files from this repo into it
  - [x] Set up your requirements/virtual environment
  - [x] Create a `data` folder and put the baseball statistics data into it
- [x] Normal mode
  - [x] Join together the relevant tables into DataFrame object(s)
  - [x] Calculate OBP of players and discard outliers
  - [x] Given a specific year, put together a 9-player roster that maximizes the OBP of the players while minimizing their salary
  - [x] Ensure that you have a complete roster with players who played at each position and that you aren't planning on using clones of players
- [ ] Hard mode
  - [ ] Adjust player salaries for inflation
  - [ ] Build an all-star moneyball dream team using the adjusted salaries

**Comment by Shea-Wolfe** [comment]
@powder-river @jamesmallen 

Not quite done yet.  Using get_years_best and get_best_pitchers will give you series you can manually pick  the best from.  Working on automating it.

https://github.com/Shea-Wolfe/moneyball

update:

Past the deadline but I wasn't happy with my submit.  Have something approximating automation and updated readme.

**Comment by powder-river** [comment]
@Shea-Wolfe in the future make sure you call you data when you turn in an ipynb. That way we can just view it in github vs having to clone it. Good submit will
