### ISSUE TITLE
15 -- Moneyball -- Bob Amand

### ISSUE THREAD

**Issue by BobAmand** [tiyd-python-2015-08/assigments#220]
- [x] Blank slate
  - [x] Create a GitHub repo called `moneyball`
  - [x] Copy all the files from this repo into it
  - [x] Set up your requirements/virtual environment
  - [x] Create a `data` folder and put the baseball statistics data into it
- [x] Normal mode
  - [x] Join together the relevant tables into DataFrame object(s)
  - [x] Calculate OBP of players and discard outliers
  - [ ] Given a specific year, put together a 9-player roster that maximizes the OBP of the players while minimizing their salary
  - [ ] Ensure that you have a complete roster with players who played at each position and that you aren't planning on using clones of players
- [ ] Hard mode
  - [ ] Adjust player salaries for inflation
  - [ ] Build an all-star moneyball dream team using the adjusted salaries

**Comment by BobAmand** [comment]
https://github.com/BobAmand/moneyball

@powder-river  @jamesmallen 
Final table requires a sort to extract the 9 position by year at the best DS.  Incomplete summary table.

**Comment by powder-river** [comment]
@BobAmand your thoughts look really scattered and it's a little tough for me to follow what's going on. That being said it appears you have the data structure in place to put a team together you just don't have a team. Given the time crunch that's a win in my book
