### ISSUE TITLE
15 -- Moneyball -- Glenn Hurley

### ISSUE THREAD

**Issue by gmhurley** [tiyd-python-2015-08/assigments#223]
- [x] Blank slate
  - [x] Create a GitHub repo called `moneyball`
  - [x] Copy all the files from this repo into it
  - [x] Set up your requirements/virtual environment
  - [x] Create a `data` folder and put the baseball statistics data into it
- [x] Normal mode
  - [x] Join together the relevant tables into DataFrame object(s)
  - [x] Calculate OBP of players and discard outliers
  - [x] Given a specific year, put together a 9-player roster that maximizes the OBP of the players while minimizing their salary
  - [x] Ensure that you have a complete roster with players who played at each position and that you aren't planning on using clones of players
- [ ] Hard mode
  - [ ] Adjust player salaries for inflation
  - [ ] Build an all-star moneyball dream team using the adjusted salaries

**Comment by gmhurley** [comment]
https://github.com/gmhurley/moneyball

**Comment by powder-river** [comment]
@gmhurley I know you refactored this already so good on you sir!
