### ISSUE TITLE
15 -- Moneyball -- Andrew Pierce

### ISSUE THREAD

**Issue by andrewmpierce** [tiyd-python-2015-08/assigments#225]
- [x] Blank slate
  - [x] Create a GitHub repo called `moneyball`
  - [x] Copy all the files from this repo into it
  - [x] Set up your requirements/virtual environment
  - [x] Create a `data` folder and put the baseball statistics data into it
- [x] Normal mode
  - [x] Join together the relevant tables into DataFrame object(s)
  - [x] Calculate OBP of players and discard outliers
  - [x] Given a specific year, put together a 9-player roster that maximizes the OBP of the players while minimizing their salary
  - [x] Ensure that you have a complete roster with players who played at each position and that you aren't planning on using clones of players
- [ ] Hard mode
  - [ ] Adjust player salaries for inflation
  - [ ] Build an all-star moneyball dream team using the adjusted salaries

**Comment by andrewmpierce** [comment]
https://github.com/andrewmpierce/moneyball
@powder-river 
Normal mode done.

Also I realized once I was almost done cleaning the data that I could have done it far more effectively than just deleting column after column, but what's done is done. It works!

**Comment by powder-river** [comment]
@andrewmpierce WHOA!!! lol. Yeah I'm guessing you've now discovered other methods such as .drop() Code looks good man!!!
