### ISSUE TITLE
16 -- Wasting Time -- Adam Hartz

### ISSUE THREAD

**Issue by ahartz1** [tiyd-python-2015-08/assigments#231]
- [x] Blank slate
  - [x] Create a GitHub repo called `atus-analysis`
  - [x] Copy all the files from this repo into it
  - [x] Set up your requirements/virtual environment
  - [x] Download the 2014 ATUS data using the `download_data.sh` script
- [x] Normal mode
  - [x] Gain an understanding of the data that is available
  - [x] Identify areas you want to compare/focus on
  - [x] Load relevant data into a notebook
  - [x] Analyze it, look for correlations, comparisons, etc.
  - [x] Present your findings in a polished notebook file (you may want to have a _scratch_ notebook for exploring, and a _final_ notebook for presentation)

**Comment by ahartz1** [comment]
SUBMIT
https://github.com/ahartz1/atus-analysis
@jamesmallen  @powder-river

**Comment by powder-river** [comment]
@ahartz1 29 commits adam, not bad at all sir, not bad at all. Solid data and great charts. Very wise to take a look and computer and math based jobs eh :) As you stated in your markdown, while there wasn't any strong correlation between income and motorsport viewership, it was interesting to see that it was fairly spread across economic classes.
