### ISSUE TITLE
16-- Wasting-Time-- Jermaine Kee

### ISSUE THREAD

**Issue by JermaineKee** [tiyd-python-2015-08/assigments#236]
- [x] Blank slate
  - [x] Create a GitHub repo called `atus-analysis`
  - [x] Copy all the files from this repo into it
  - [x] Set up your requirements/virtual environment
  - [x] Download the 2014 ATUS data using the `download_data.sh` script
- [x] Normal mode
  - [x] Gain an understanding of the data that is available
  - [x] Identify areas you want to compare/focus on
  - [x] Load relevant data into a notebook
  - [x] Analyze it, look for correlations, comparisons, etc.
  - [ ] Present your findings in a polished notebook file (you may want to have a _scratch_ notebook for exploring, and a _final_ notebook for presentation)

**Comment by JermaineKee** [comment]
https://github.com/keezeopendoors/Atus-Analysis

Very rough... didnt have time to clean it up, but there are charts and comparisons
@jamesmallen 
@powder-river

**Comment by powder-river** [comment]
@keezeopendoors so i'll let @jamesmallen  be the final judge on this matter. It looks like you have charts that represent data, but I don't really see correlations. For example you have the data that shows how parents spend time with kids, but you don't do compare that data against anything else. for example, do parent's who spend time doing homework with kid's tend to have a higher educational background? Something to that affect.

**Comment by JermaineKee** [comment]
https://github.com/keezeopendoors/Atus-Analysis

added a comparison on reading to kids, let me know if this works

@powder-river 
@jamesmallen
