### ISSUE TITLE
16 -- wasting time -- Will Butts

### ISSUE THREAD

**Issue by Shea-Wolfe** [tiyd-python-2015-08/assigments#237]
- [x] Blank slate
  - [x] Create a GitHub repo called `atus-analysis`
  - [x] Copy all the files from this repo into it
  - [x] Set up your requirements/virtual environment
  - [x] Download the 2014 ATUS data using the `download_data.sh` script
- [x] Normal mode
  - [x] Gain an understanding of the data that is available
  - [x] Identify areas you want to compare/focus on
  - [x] Load relevant data into a notebook
  - [x] Analyze it, look for correlations, comparisons, etc.
  - [x] Present your findings in a polished notebook file (you may want to have a _scratch_ notebook for exploring, and a _final_ notebook for presentation)

**Comment by Shea-Wolfe** [comment]
@jamesmallen @powder-river 

https://github.com/Shea-Wolfe/atus-analysis.

A little light on charts currently but some interesting data.

**Comment by powder-river** [comment]
@Shea-Wolfe why you make me scroll so much! data looks good. The hockey findings in particular are interesting I must say. I'd be curious to know more info about that data set in particular

**Comment by Shea-Wolfe** [comment]
@powder-river Make up your mind man.  Last assignment it is include more checkpoints, this assignment it is don't make me scroll so much :P.
