### ISSUE TITLE
16 -- Wasting-Time -- Bob Amand

### ISSUE THREAD

**Issue by BobAmand** [tiyd-python-2015-08/assigments#238]
- [x] Blank slate
  - [x] Create a GitHub repo called `atus-analysis`
  - [x] Copy all the files from this repo into it
  - [x] Set up your requirements/virtual environment
  - [x] Download the 2014 ATUS data using the `download_data.sh` script
- [x] Normal mode
  - [x] Gain an understanding of the data that is available
  - [x] Identify areas you want to compare/focus on
  - [x] Load relevant data into a notebook
  - [x] Analyze it, look for correlations, comparisons, etc.
  - [x] Present your findings in a polished notebook file (you may want to have a _scratch_ notebook for exploring, and a _final_ notebook for presentation)

**Comment by BobAmand** [comment]
https://github.com/BobAmand/atus-analysis

@powder-river  @jamesmallen

**Comment by powder-river** [comment]
@BobAmand my man, awesome weekend assignment. As we've talked about already you've really been upping your game the last couple of weeks. You seem to take to the data science aspect of python very well and it shows in this assignment. 

Now on the other hand you have like 6 python notebooks and it took me forever to find the *\* right *\* one to review. A good README can solve that headache. 

Now I really appreciate you cleaning your data. It makes it so much easier when I have a label of 'Income' as opposed to 'TUINCDDOOADEXX'. It really makes a world of difference in terms of readability. That being said you didn't just clean your data, you bleached it, boiled it, gave it vaccines,  and sent in through CDC level decontamination. In the future I would just bring in the data you know that you need and clean that as opposed to relabeling all of the data. It will save you a TON of time. Great work bob. Keep it up as we head into machine learning and web dev.
