### ISSUE TITLE
16--Wasting Time--Kathleen Rauh

### ISSUE THREAD

**Issue by nckathleen** [tiyd-python-2015-08/assigments#239]
- [x] Blank slate
  - [x] Create a GitHub repo called `atus-analysis`
  - [x] Copy all the files from this repo into it
  - [x] Set up your requirements/virtual environment
  - [x] Download the 2014 ATUS data using the `download_data.sh` script
- [ ] Normal mode
  - [x] Gain an understanding of the data that is available
  - [x] Identify areas you want to compare/focus on
  - [x] Load relevant data into a notebook
  - [x] Analyze it, look for correlations, comparisons, etc.
  - [ ] Present your findings in a polished notebook file (you may want to have a _scratch_ notebook for exploring, and a _final_ notebook for presentation)

**Comment by nckathleen** [comment]
https://github.com/nckathleen/ATUS-Analysis

@jamesmallen @powder-river

**Comment by powder-river** [comment]
@nckathleen overall good work. I would recommend trying to clean your data more for readability. I applaud you for having Markdown cells that give me the play by play, however having labels in place of 32,34,35,36,etc. can be powerful. Also, I am having trouble understanding what your blue bar is on your histograph? 

You data is interesting, I'm curious if there is data out there that could show us why more men than women are achieving higher education goals. Your data did not tell me was this just overall men just are more represented in education or is it more men finished?
