### ISSUE TITLE
01 -- Fly Your Flag -- Jonathan Frederick

### ISSUE THREAD

**Issue by JonathanFrederick** [tiyd-python-2015-08/assigments#24]
- [x] Code It
  - [x] Draw a flag with one or more turtles
- [x] Press the Issue
  - [x] Open a _WIP issue_ named `01 -- Fly Your Flag -- YOUR NAME`
  - [x] Put this task list in the description
  - [x] Check off the boxes as you complete items
  - [x] Add a comment with the _Share_ link to your flag
- [x] Hard Mode (optional)
  - [x] Move flag drawing code to a function
  - [x] Add a parameter to the function called size
  - [x] Test your flag drawing at various sizes to ensure it works

**Comment by JonathanFrederick** [comment]
https://trinket.io/python/f97c7989fd

**Comment by JonathanFrederick** [comment]
Hard Mode
https://trinket.io/python/bd25857c36

**Comment by JonathanFrederick** [comment]
SUBMIT
@jamesmallen 
@powder-river

**Comment by powder-river** [comment]
@JonathanFrederick good work! I want you to go back to your code as a user. type in potato as the first response. how might you improve upon your code now?
