### ISSUE TITLE
16 -- Wasting Time -- Andrew Pierce

### ISSUE THREAD

**Issue by andrewmpierce** [tiyd-python-2015-08/assigments#240]
- [x] Blank slate
  - [x] Create a GitHub repo called `atus-analysis`
  - [x] Copy all the files from this repo into it
  - [x] Set up your requirements/virtual environment
  - [x] Download the 2014 ATUS data using the `download_data.sh` script
- [x] Normal mode
  - [x] Gain an understanding of the data that is available
  - [x] Identify areas you want to compare/focus on
  - [x] Load relevant data into a notebook
  - [x] Analyze it, look for correlations, comparisons, etc.
  - [x] Present your findings in a polished notebook file (you may want to have a _scratch_ notebook for exploring, and a _final_ notebook for presentation)

**Comment by andrewmpierce** [comment]
https://github.com/andrewmpierce/time-analysis
@powder-river 
Submitting weekend work. The FINAL_ATUS notebook contains the finished work, the time-analysis is a scratch folder.

**Comment by powder-river** [comment]
@andrewmpierce your code and charts are solid andrew but what really shines is the explanation you give to all of your data. I found it was very clear what I was looking at and what the numbers meant. Back in college I had a professor for technical writing that said "if you don't tell your reader what to thank, then who knows what they'll think". Your commentary solves this problem very well  by explaining what the data means
