### ISSUE TITLE
17 -- Signs of Regression -- Bob Amand

### ISSUE THREAD

**Issue by BobAmand** [tiyd-python-2015-08/assigments#246]
- [x] Blank slate
  - [x] Create a GitHub repo called `linear-regression`
  - [x] Copy all the files from this repo into it
  - [x] Set up your requirements/virtual environment
- [x] Normal mode
  - [x] Complete the tasks in the `simple-linear-regression.ipynb` file
    - [x] Ground cricket chirps
    - [x] Brain vs. Body Weight
    - [x] Salary Discrimination
  - [x] Make sure your findings are well-organized, using Markdown headers and formatting to separate sections
  - [x] Ensure your notebook runs when all the outputs are cleared and the cells are run in order (restart your kernel, clear all outputs, and run all cells)
- [ ] Hard mode
  - [ ] Find another source of data that you suspect may have a single- or multiple-linear relationship
  - [ ] Attempt to find a best fit model for the data
  - [ ] Report your findings, showing chart(s) as necessary

**Comment by BobAmand** [comment]
https://github.com/BobAmand/linear-regression

@powder-river  @jamesmallen

**Comment by jmaroeder** [comment]
Great submission - please make sure that your notebook files include the output by running all the cells before you commit/push, though!

**Comment by BobAmand** [comment]
Thanks James.   I misunderstood the appropriate notebook parking and will trigger all for the next submission. 

Regards,
Bob

Robert E. Amand
Biotherapeutic Modeling Group, Inc.
(919) 244-1487 cell
(919) 465-9584 land
biotmg@nc.rr.com
