### ISSUE TITLE
17 -- signs of regression -- Will Butts 

### ISSUE THREAD

**Issue by Shea-Wolfe** [tiyd-python-2015-08/assigments#251]
- [x] Blank slate
  - [x] Create a GitHub repo called `linear-regression`
  - [x] Copy all the files from this repo into it
  - [x] Set up your requirements/virtual environment
- [x] Normal mode
  - [x] Complete the tasks in the `simple-linear-regression.ipynb` file
    - [x] Ground cricket chirps
    - [x] Brain vs. Body Weight
    - [x] Salary Discrimination
  - [x] Make sure your findings are well-organized, using Markdown headers and formatting to separate sections
  - [x] Ensure your notebook runs when all the outputs are cleared and the cells are run in order (restart your kernel, clear all outputs, and run all cells)
- [ ] Hard mode
  - [ ] Find another source of data that you suspect may have a single- or multiple-linear relationship
  - [ ] Attempt to find a best fit model for the data
  - [ ] Report your findings, showing chart(s) as necessary

**Comment by Shea-Wolfe** [comment]
@jamesmallen @powder-river 

https://github.com/Shea-Wolfe/linear-regression

normal mode complete, taking a look at hard.

**Comment by powder-river** [comment]
@Shea-Wolfe good code, good charts. my comments:
- don't be afraid to add markdown or comments to your code. It gets thick at some points 
- don't forget to elaborate on your cricket, and brain/body data

good work overall. (commits?) ++
