### ISSUE TITLE
18 -- Plaid Coat -- Adam Hartz

### ISSUE THREAD

**Issue by ahartz1** [tiyd-python-2015-08/assigments#256]
- [x] Blank slate
  - [x] Create a GitHub repo called `car-linear-regression`
  - [x] Copy all the files from this repo into it
  - [x] Set up your requirements/virtual environment
- [x] Normal mode
  - [x] Complete the tasks in the `car-worth.ipynb` file
  - [x] Make sure your findings are well-organized, using Markdown headers and formatting to separate sections
  - [x] Ensure your notebook runs when all the outputs are cleared and the cells are run in order (restart your kernel, clear all outputs, and run all cells)

**Comment by ahartz1** [comment]
SUBMIT
https://github.com/ahartz1/car-linear-regression
@jamesmallen @powder-river

**Comment by powder-river** [comment]
@ahartz1 obviously we looked over your code during class so well done my friend
