### ISSUE TITLE
18 -- Plaid Coat -- Ryan Burton

### ISSUE THREAD

**Issue by rryanburton** [tiyd-python-2015-08/assigments#258]
- [x] Blank slate
  - [x] Create a GitHub repo called `car-linear-regression`
  - [x] Copy all the files from this repo into it
  - [x] Set up your requirements/virtual environment
- [ ] Normal mode
  - [ ] Complete the tasks in the `car-worth.ipynb` file
  - [x] Make sure your findings are well-organized, using Markdown headers and formatting to separate sections
  - [x] Ensure your notebook runs when all the outputs are cleared and the cells are run in order (restart your kernel, clear all outputs, and run all cells)

**Comment by rryanburton** [comment]
https://github.com/rryanburton/car-linear-regression/

@powder-river 
@jamesmallen

**Comment by powder-river** [comment]
@rryanburton great job working through your code. I get a lot of you got hung up on task three but hopefully HW review helped you out there with the dummy variables.
