### ISSUE TITLE
18--Plaid Coat--Kathleen Rauh

### ISSUE THREAD

**Issue by nckathleen** [tiyd-python-2015-08/assigments#259]
- [x] Blank slate
  - [x] Create a GitHub repo called `car-linear-regression`
  - [x] Copy all the files from this repo into it
  - [x] Set up your requirements/virtual environment
- [ ] Normal mode
  - [ ] Complete the tasks in the `car-worth.ipynb` file
  - [x] Make sure your findings are well-organized, using Markdown headers and formatting to separate sections
  - [x] Ensure your notebook runs when all the outputs are cleared and the cells are run in order (restart your kernel, clear all outputs, and run all cells)

**Comment by nckathleen** [comment]
https://github.com/nckathleen/Car-Linear-Regression
@jamesmallen @powder-river

**Comment by powder-river** [comment]
@nckathleen really solid effort on your part for this one. I know you were racking your brain pretty good on this one and that's a good thing. It looks like you had several breakthroughs with your data as you went along so be proud of what you accomplished! hopefully it's all come together somewhat now that you have gone through hw review.
