### ISSUE TITLE
18 -- Plaid Coat -- Will Butts

### ISSUE THREAD

**Issue by Shea-Wolfe** [tiyd-python-2015-08/assigments#261]
- [x] Blank slate
  - [x] Create a GitHub repo called `car-linear-regression`
  - [x] Copy all the files from this repo into it
  - [x] Set up your requirements/virtual environment
- [x] Normal mode
  - [x] Complete the tasks in the `car-worth.ipynb` file
  - [x] Make sure your findings are well-organized, using Markdown headers and formatting to separate sections
  - [x] Ensure your notebook runs when all the outputs are cleared and the cells are run in order (restart your kernel, clear all outputs, and run all cells)

**Comment by Shea-Wolfe** [comment]
@powder-river @jamesmallen 

https://github.com/Shea-Wolfe/car-linear-regression

Ready to go.  Big thanks to Jonathan for helping me break through what to do with our dummy variable columns.

**Comment by powder-river** [comment]
@Shea-Wolfe ooooooo pretty polynomial charts!!! solid solid submission will. Great data representation and good use of polynomial regression
