### ISSUE TITLE
18 -- Plaid-Coat -- Karthik Kasala

### ISSUE THREAD

**Issue by kasalak** [tiyd-python-2015-08/assigments#262]
- [x] Blank slate
  - [x] Create a GitHub repo called `car-linear-regression`
  - [x] Copy all the files from this repo into it
  - [x] Set up your requirements/virtual environment
- [ ] Normal mode
  - [ ] Complete the tasks in the `car-worth.ipynb` file
  - [x] Make sure your findings are well-organized, using Markdown headers and formatting to separate sections
  - [x] Ensure your notebook runs when all the outputs are cleared and the cells are run in order (restart your kernel, clear all outputs, and run all cells)

**Comment by kasalak** [comment]
* [ ] Blank slate
  * [ ] Create a GitHub repo called `car-linear-regression`
  * [ ] Copy all the files from this repo into it
  * [ ] Set up your requirements/virtual environment
* [ ] Normal mode
  * [ ] Complete the tasks in the `car-worth.ipynb` file
  * [ ] Make sure your findings are well-organized, using Markdown headers and formatting to separate sections
  * [ ] Ensure your notebook runs when all the outputs are cleared and the cells are run in order (restart your kernel, clear all outputs, and run all cells)

**Comment by kasalak** [comment]
https://github.com/kasalak/Plaid-Coat

**Comment by powder-river** [comment]
@kasalak looks like you were very much on the cusp of getting through part 3. hopefully you understand it now after HW review
