### ISSUE TITLE
18--Plaid-Coat-- Jermaine Kee

### ISSUE THREAD

**Issue by JermaineKee** [tiyd-python-2015-08/assigments#263]
- [x] Blank slate
  - [x] Create a GitHub repo called `car-linear-regression`
  - [x] Copy all the files from this repo into it
  - [x] Set up your requirements/virtual environment
- [x] Normal mode
  - [x] Complete the tasks in the `car-worth.ipynb` file
  - [x] Make sure your findings are well-organized, using Markdown headers and formatting to separate sections
  - [x] Ensure your notebook runs when all the outputs are cleared and the cells are run in order (restart your kernel, clear all outputs, and run all cells)

**Comment by JermaineKee** [comment]
https://github.com/keezeopendoors/car-linear-regression

open car-worth-work.ipynb

@jamesmallen 
@powder-river

**Comment by powder-river** [comment]
@keezeopendoors good job jermaine. Hopefully you understand part 3 better after HW review in class today.  It looks like you understand itertools.combinations now which is good
