### ISSUE TITLE
18 -- Plaid Coat -- Andrew Pierce

### ISSUE THREAD

**Issue by andrewmpierce** [tiyd-python-2015-08/assigments#264]
- [x] Blank slate
  - [x] Create a GitHub repo called `car-linear-regression`
  - [x] Copy all the files from this repo into it
  - [x] Set up your requirements/virtual environment
- [x] Normal mode
  - [x] Complete the tasks in the `car-worth.ipynb` file
  - [x] Make sure your findings are well-organized, using Markdown headers and formatting to separate sections
  - [x] Ensure your notebook runs when all the outputs are cleared and the cells are run in order (restart your kernel, clear all outputs, and run all cells)

**Comment by andrewmpierce** [comment]
https://github.com/andrewmpierce/Car-Worth
@powder-river 
Submitted

**Comment by powder-river** [comment]
@andrewmpierce thank your for giving me a clean note book! For that I make you the winner(didn't even know this was a contest did you).

on a serious note though excellent code. I see many of you found the revelation that a caddy convertible seems to hold it's value. well done well done
