### ISSUE TITLE
18 -- Plaid Coat -- Jonathan Frederick

### ISSUE THREAD

**Issue by JonathanFrederick** [tiyd-python-2015-08/assigments#265]
- [x] Blank slate
  - [x] Create a GitHub repo called `car-linear-regression`
  - [x] Copy all the files from this repo into it
  - [x] Set up your requirements/virtual environment
- [x] Normal mode
  - [x] Complete the tasks in the `car-worth.ipynb` file
  - [x] Make sure your findings are well-organized, using Markdown headers and formatting to separate sections
  - [x] Ensure your notebook runs when all the outputs are cleared and the cells are run in order (restart your kernel, clear all outputs, and run all cells)

**Comment by JonathanFrederick** [comment]
@jamesmallen @powder-river 

https://github.com/JonathanFrederick/car-linear-regression

**Comment by powder-river** [comment]
@JonathanFrederick i was impressed by the fact that you found such high correlation, though seeing as you were looking at cadillac perhaps I should expect that. Did you use dummy variables?
