### ISSUE TITLE
18 -- Plaid-Coat -- Glenn Hurley

### ISSUE THREAD

**Issue by gmhurley** [tiyd-python-2015-08/assigments#267]
- [x] Blank slate
  - [x] Create a GitHub repo called `car-linear-regression`
  - [x] Copy all the files from this repo into it
  - [x] Set up your requirements/virtual environment
- [x] Normal mode
  - [x] Complete the tasks in the `car-worth.ipynb` file
  - [x] Make sure your findings are well-organized, using Markdown headers and formatting to separate sections
  - [x] Ensure your notebook runs when all the outputs are cleared and the cells are run in order (restart your kernel, clear all outputs, and run all cells)

**Comment by gmhurley** [comment]
https://github.com/gmhurley/car-linear-regression

**Comment by powder-river** [comment]
@gmhurley looks like you got all the requirements knocked out, though I will be forever scarred by the amount of scrolling in part 3 ..... the horror......

good job glen!
