### ISSUE TITLE
01 -- Fly your Flag -- Jermaine

### ISSUE THREAD

**Issue by JermaineKee** [tiyd-python-2015-08/assigments#27]
- [x] Code It
  - [x] Draw a flag with one or more turtles
- [x] Press the Issue
  - [x] Open a _WIP issue_ named `01 -- Fly Your Flag -- YOUR NAME`
  - [x] Put this task list in the description
  - [x] Check off the boxes as you complete items
  - [x] Add a comment with the _Share_ link to your flag
- [ ] Hard Mode (optional)
  - [ ] Move flag drawing code to a function
  - [ ] Add a paramter to the function called size
  - [ ] Test your flag drawing at various sizes to ensure it works

**Comment by keezeopendoors** [comment]
https://james_allen_theironyard_com.trinket.io/turtles#/turtles/drawing-with-the-turtle

it's the main.py

**Comment by JermaineKee** [comment]
https://trinket.io/python/e19e62ff12 @jamesmallen  @powder-river

**Comment by powder-river** [comment]
@keezeopendoors good representation of Brazil. I have proposed this question to a few others so I'll ask you the same question.

Although we haven't covered it in class yet recall functions from the rework. How do you think your code would look from a readability standpoint if your organized it in functions? Do you think the code would be easier to understand?

def draw_globe()
code
code
code

def draw_diamond()
code
code
code
