### ISSUE TITLE
19 -- Spamalot --Tyler Kotkin

### ISSUE THREAD

**Issue by TylerKotkin** [tiyd-python-2015-08/assigments#271]
- [x] Blank slate
  - [x] Create a GitHub repo called `spambase`
  - [x] Set up your requirements/virtual environment
  - [x] Download the spambase dataset, but do not commit it to your repository
  - [x] Create an IPython notebook to write your code and collect your findings
- [x] Normal mode
  - [x] Load in the data file, doing any cleaning necessary to get usable data
  - [x] Subsample the data set into training and test data
  - [x] Write code to classify the data into spam/not-spam, making sure that you just use your training data to build your model, and checking your results with your test data
- [ ] Hard mode
  - [ ] Try reducing or changing your features in order to get better results
  - [ ] Find another dataset and break it down into features
  - [ ] Test your algorthm on the new dataset and compare its performance

**Comment by TylerKotkin** [comment]
https://github.com/TylerKotkin/spambase

**Comment by powder-river** [comment]
@TylerKotkin I like that your entire read me is just 

### spambase

got a good chuckle from that
good job tyler!
