### ISSUE TITLE
01 -- Fly Your Flag -- Tyler Kotkin

### ISSUE THREAD

**Issue by TylerKotkin** [tiyd-python-2015-08/assigments#28]
- [x] Code It
  - [x] Draw a flag with one or more turtles
- [x] Press the Issue
  - [x] Open a _WIP issue_ named `01 -- Fly Your Flag -- YOUR NAME`
  - [x] Put this task list in the description
  - [x] Check off the boxes as you complete items
  - [x] Add a comment with the _Share_ link to your flag
- [x] Hard Mode (optional)
  - [x] Move flag drawing code to a function
  - [x] Add a paramter to the function called size
  - [x] Test your flag drawing at various sizes to ensure it works

**Comment by TylerKotkin** [comment]
https://trinket.io/python/1d58927ca2

**Comment by TylerKotkin** [comment]
better centering 

https://trinket.io/python/23f41d4b3f

**Comment by TylerKotkin** [comment]
submitted 
@jamesmallen 
@powder-river

**Comment by powder-river** [comment]
@TylerKotkin great flag! be careful how you word things when asking for user input. you asked what size of flag do you want. I typed in medium and got an error. Obviously you wanted a number but we will talk more about how to ask for user input
