### ISSUE TITLE
01 -- Fly Your Flag -- Adam Hartz

### ISSUE THREAD

**Issue by ahartz1** [tiyd-python-2015-08/assigments#29]
- [x] Code It
  - [x] Draw a flag with one or more turtles
- [x] Press the Issue
  - [x] Open a _WIP issue_ named `01 -- Fly Your Flag -- YOUR NAME`
  - [x] Put this task list in the description
  - [x] Check off the boxes as you complete items
  - [x] Add a comment with the _Share_ link to your flag
- [x] Hard Mode (optional)
  - [x] Move flag drawing code to a function
  - [x] Add a paramter to the function called size
  - [x] Test your flag drawing at various sizes to ensure it works

**Comment by ahartz1** [comment]
https://trinket.io/python/a8d1c11377

SUBMIT
@powder-river @jamesmallen

**Comment by jmaroeder** [comment]
'Merica!

Looks really good. Excellent job considering issues with the user input and using exceptions to catch the - although if someone enters an incorrect size ~1,000 times, you'll likely run into issues with the program crashing. :smirk_cat:
