### ISSUE TITLE
21 -- Reverse Engineering CSS -- Adam Hartz

### ISSUE THREAD

**Issue by ahartz1** [tiyd-python-2015-08/assigments#292]
- [x] Blank slate
  - [x] Create a CodePen account
- [x] Normal mode
  - [x] Create a pen for the Shakespeare sonnet
  - [x] Create a pen for the complicated button
- [ ] Hard mode
  - [ ] Create a pen for the GitHub repositories page
- [ ] Nightmare mode
  - [ ] Create a pen for the Surf and Paddle co. page

**Comment by ahartz1** [comment]
SUBMIT (Too tired to continue.)
http://codepen.io/ahartz1/pen/gaWYzV
http://codepen.io/ahartz1/pen/EVmgoP
@jamesmallen @powder-river

**Comment by powder-river** [comment]
@ahartz1 not bad adam. For the stars checkout unicode chars...
