### ISSUE TITLE
21 -- Reverse Engineering CSS -- Karthik Kasala

### ISSUE THREAD

**Issue by kasalak** [tiyd-python-2015-08/assigments#293]
- [x] Blank slate
  - [x] Create a CodePen account
- [x] Normal mode
  - [x] Create a pen for the Shakespeare sonnet
  - [x] Create a pen for the complicated button
- [ ] Hard mode
  - [ ] Create a pen for the GitHub repositories page
- [ ] Nightmare mode
  - [ ] Create a pen for the Surf and Paddle co. page

**Comment by kasalak** [comment]
Close, but no cigar.

http://codepen.io/karthikkasala/

**Comment by powder-river** [comment]
@kasalak but close enough for government work. A note: in general it's bad practice to apply style in your html, use your css for all of your style
