### ISSUE TITLE
21 -- Reverse Engineering CSS -- Andrew Pierce

### ISSUE THREAD

**Issue by andrewmpierce** [tiyd-python-2015-08/assigments#298]
- [x] Blank slate
  - [x] Create a CodePen account
- [x] Normal mode
  - [x] Create a pen for the Shakespeare sonnet
  - [x] Create a pen for the complicated button
- [ ] Hard mode
  - [ ] Create a pen for the GitHub repositories page
- [ ] Nightmare mode
  - [ ] Create a pen for the Surf and Paddle co. page

**Comment by andrewmpierce** [comment]
http://codepen.io/andrewmpierce/pen/ojWjWK
http://codepen.io/andrewmpierce/pen/wKdGGb
@powder-river 
Submitted.

**Comment by powder-river** [comment]
@andrewmpierce outstanding work andrew, hopefully you understand the html/css barebones basics.
