### ISSUE TITLE
21--Reverse-Engineering-CSS--Jonathan Frederick

### ISSUE THREAD

**Issue by JonathanFrederick** [tiyd-python-2015-08/assigments#299]
- [x] Blank slate
  - [x] Create a CodePen account
- [x] Normal mode
  - [x] Create a pen for the Shakespeare sonnet
  - [x] Create a pen for the complicated button
- [ ] Hard mode
  - [ ] Create a pen for the GitHub repositories page
- [ ] Nightmare mode
  - [ ] Create a pen for the Surf and Paddle co. page

**Comment by JonathanFrederick** [comment]
Sonnet:
http://codepen.io/jonFrederick/pen/yYbNMJ
Button with proper gradiants:
http://codepen.io/jonFrederick/pen/XmRdLE
Button with proper borders:
http://codepen.io/jonFrederick/pen/XmRNVa?editors=010

**Comment by JonathanFrederick** [comment]
@jamesmallen @powder-river

**Comment by powder-river** [comment]
@JonathanFrederick sonet and buttons look good. Why did you choose to go with an h6 tag for your description out of curiosity?

**Comment by JonathanFrederick** [comment]
@powder-river Just to have something that wasn't a &#x3008;p&#x3009; to skip using class or id there?
