### ISSUE TITLE
21 -- Reverse engineering CSS -- Will Butts

### ISSUE THREAD

**Issue by Shea-Wolfe** [tiyd-python-2015-08/assigments#300]
- [x] Blank slate
  - [x] Create a CodePen account
- [x] Normal mode
  - [x] Create a pen for the Shakespeare sonnet
  - [x] Create a pen for the complicated button
- [ ] Hard mode
  - [ ] Create a pen for the GitHub repositories page
- [ ] Nightmare mode
  - [ ] Create a pen for the Surf and Paddle co. page

**Comment by Shea-Wolfe** [comment]
@jamesmallen @powder-river 

Shakespeare http://codepen.io/Shea-Wolfe/pen/EVmVpJ?editors=110

**Comment by Shea-Wolfe** [comment]
@jamesmallen @powder-river 

checkout http://codepen.io/Shea-Wolfe/pen/MameOG?editors=110

credit to Jon for helping me with the unicode star character number.  Not fully happy with the inner edge contrast.  About to fix the font but wanted a submit before deadline.

edit: fixed the font up.  done at 12:55

**Comment by powder-river** [comment]
@Shea-Wolfe looking good. Good css implementation to capitalize your sonet lines
