### ISSUE TITLE
21 -- Reverse engineering CSS -- Jermaine Kee

### ISSUE THREAD

**Issue by JermaineKee** [tiyd-python-2015-08/assigments#301]
- [x] Blank slate
  - [x] Create a CodePen account
- [x] Normal mode
  - [x] Create a pen for the Shakespeare sonnet
  - [x] Create a pen for the complicated button
- [ ] Hard mode
  - [ ] Create a pen for the GitHub repositories page
- [ ] Nightmare mode
  - [ ] Create a pen for the Surf and Paddle co. page

**Comment by JermaineKee** [comment]
http://codepen.io/JermaineKee/pen/dYWMeg?editors=110
http://codepen.io/JermaineKee/pen/ojWzaw
@jamesmallen 
@powder-river

**Comment by powder-river** [comment]
@JermaineKee good submit, hopefully you feel like  you have some basic html/css knowledge now. I'll leave you with two things:
- what is a gradient, take a closer look at the original button, how could you implement a gradient?
- in general we like the style with css over html. how could you make the text that needs to be bold, bold without using the bold tag?
