### ISSUE TITLE
21 -- Reverse engineering CSS -- Glenn Hurley

### ISSUE THREAD

**Issue by gmhurley** [tiyd-python-2015-08/assigments#302]
- [x] Blank slate
  - [x] Create a CodePen account
- [x] Normal mode
  - [x] Create a pen for the Shakespeare sonnet
  - [x] Create a pen for the complicated button
- [ ] Hard mode
  - [ ] Create a pen for the GitHub repositories page
- [ ] Nightmare mode
  - [ ] Create a pen for the Surf and Paddle co. page

**Comment by gmhurley** [comment]
http://codepen.io/gmhurley/pen/MamaLP?editors=110

**Comment by gmhurley** [comment]
http://codepen.io/gmhurley/pen/QjvyzR?editors=110

**Comment by powder-river** [comment]
@gmhurley looking good all around
