### ISSUE TITLE
21 -- Reverse Engineering -- Ryan Burton

### ISSUE THREAD

**Issue by rryanburton** [tiyd-python-2015-08/assigments#303]
- [x] Blank slate
  - [x] Create a CodePen account
- [x] Normal mode
  - [x] Create a pen for the Shakespeare sonnet
  - [x] Create a pen for the complicated button
- [ ] Hard mode
  - [ ] Create a pen for the GitHub repositories page
- [ ] Nightmare mode
  - [ ] Create a pen for the Surf and Paddle co. page

**Comment by rryanburton** [comment]
sonnet:  http://codepen.io/rryanburton/pen/JYNdQm
button:  http://codepen.io/rryanburton/pen/ojWzLL

@powder-river 
@jamesmallen

**Comment by powder-river** [comment]
@rryanburton outstanding button! how can you now center your sonet using the box model?
