### ISSUE TITLE
22 -- MovieLens Online -- Adam Hartz

### ISSUE THREAD

**Issue by ahartz1** [tiyd-python-2015-08/assigments#305]
- [x] Night 1
  - [x] Miscellaneous
    - [x] Make commits after every significant change
    - [x] Use feature branches whenever you add something to a stable product
    - [x] Use requirements.txt and Django best practices for laying out your project
  - [x] Normal mode
    - [x] Create a Django project called movieratings
    - [x] Create a Django app inside your project
    - [x] Create models for users (raters), movies, and ratings
    - [x] Create Django admin pages for the models
  - [ ] Hard mode
    - [ ] Add methods to your models
    - [ ] Test your methods

**Comment by ahartz1** [comment]
SUBMIT Normal Mode
https://github.com/ahartz1/movieratings
@jamesmallen @powder-river

**Comment by powder-river** [comment]
@ahartz1 excellent work on your django project so far, i really enjoy your admin page, very easy to understand
