### ISSUE TITLE
22 -- MovieLens-Online -- Ryan Burton

### ISSUE THREAD

**Issue by rryanburton** [tiyd-python-2015-08/assigments#306]
- [ ] Night 1
  - [ ] Miscellaneous
    - [x] Make commits after every significant change
    - [ ] Use feature branches whenever you add something to a stable product
    - [x] Use requirements.txt and Django best practices for laying out your project
  - [x] Normal mode
    - [x] Create a Django project called movieratings
    - [x] Create a Django app inside your project
    - [x] Create models for users (raters), movies, and ratings
    - [x] Create Django admin pages for the models
  - [ ] Hard mode
    - [ ] Add methods to your models
    - [ ] Test your methods

**Comment by rryanburton** [comment]
https://github.com/rryanburton/django-movies

**Comment by powder-river** [comment]
@rryanburton solid first django run. a note:

when working in a model you don't need to create an id for that model, it is created automatically .
for example you created a movie_id field in the movie model but you don't need that, same with this user_id in the rater field, they have id's automatically
