### ISSUE TITLE
22 -- MovieLens-Online -- Jonathan Frederick

### ISSUE THREAD

**Issue by JonathanFrederick** [tiyd-python-2015-08/assigments#307]
- [x] Night 1
  - [x] Miscellaneous
    - [x] Make commits after every significant change
    - [x] Use feature branches whenever you add something to a stable product
    - [x] Use requirements.txt and Django best practices for laying out your project
  - [x] Normal mode
    - [x] Create a Django project called movieratings
    - [x] Create a Django app inside your project
    - [x] Create models for users (raters), movies, and ratings
    - [x] Create Django admin pages for the models
  - [ ] Hard mode
    - [ ] Add methods to your models
    - [ ] Test your methods

**Comment by JonathanFrederick** [comment]
@jamesmallen @powder-river 
Is this all we're looking for tonight?
https://github.com/JonathanFrederick/django-movies

**Comment by powder-river** [comment]
@JonathanFrederick so it looks like it's blowing up when you try to create a rating. so check that out before moving on. Also, i see you have rating inside rating as an int and movie inside a movie as an int.

It feels like you're meaning to assign an id??? note that you don't have to assign an id inside a model. so if i am in my Movie model, everytime I create a movie, it assigns it an id automatically.
