### ISSUE TITLE
22 -- MovieLens-Online -- Karthik Kasala

### ISSUE THREAD

**Issue by kasalak** [tiyd-python-2015-08/assigments#308]
- [x] Night 1
  - [x] Miscellaneous
    - [x] Make commits after every significant change
    - [x] Use feature branches whenever you add something to a stable product
    - [x] Use requirements.txt and Django best practices for laying out your project
  - [x] Normal mode
    - [x] Create a Django project called movieratings
    - [x] Create a Django app inside your project
    - [x] Create models for users (raters), movies, and ratings
    - [x] Create Django admin pages for the models
  - [ ] Hard mode
    - [ ] Add methods to your models
    - [ ] Test your methods

**Comment by kasalak** [comment]
https://github.com/kasalak/MovieLens-Online

**Comment by powder-river** [comment]
@kasalak looked at yours in class so hopefully you took in all the feedback! good job
