### ISSUE TITLE
01-- Fly Your Flag -- Andrew Pierce

### ISSUE THREAD

**Issue by andrewmpierce** [tiyd-python-2015-08/assigments#31]
[ ] Code It
- [x] Draw a flag with one or more turtles
  - [x] Press the Issue
- [x] Open a _WIP issue_ named `01 -- Fly Your Flag -- YOUR NAME`
- [x] Put this task list in the description
- [x] Check off the boxes as you complete items
- [x] Add a comment with the _Share_ link to your flag
  - [x] Hard Mode (optional)
- [x] Move flag drawing code to a function
- [x] Add a paramter to the function called size
- [x] Test your flag drawing at various sizes to ensure it works

**Comment by andrewmpierce** [comment]
https://trinket.io/python/ca5fca1bd2 (regular mode)

https://trinket.io/python/15ee3eb0bb (hard mode)

**Comment by andrewmpierce** [comment]
Submitted

**Comment by powder-river** [comment]
@apierce1992 great job on your flag. I saw you used one large function in your hard mode and none in normal. Just food for thought. what if you broke your code into functions that had specific tasks.

def draw_star()
code
code
code

def draw_outline()
code
code
code

what do you think that does for readability?
