### ISSUE TITLE
22 -- MovieLens-Online -- Glenn Hurley

### ISSUE THREAD

**Issue by gmhurley** [tiyd-python-2015-08/assigments#310]
- [ ] Night 1
  - [ ] Miscellaneous
    - [ ] Make commits after every significant change
    - [ ] Use feature branches whenever you add something to a stable product
    - [ ] Use requirements.txt and Django best practices for laying out your project
  - [x] Normal mode
    - [x] Create a Django project called movieratings
    - [x] Create a Django app inside your project
    - [x] Create models for users (raters), movies, and ratings
    - [x] Create Django admin pages for the models
  - [ ] Hard mode
    - [ ] Add methods to your models
    - [ ] Test your methods

**Comment by gmhurley** [comment]
https://github.com/gmhurley/movieratings

**Comment by powder-river** [comment]
@gmhurley low on commits :(  also did you forget a push? we had talked about not needing a model id of itself in the model, i.e. don't need movie_id in the movie model? also some string methods in your model will help clean up your admin page

**Comment by gmhurley** [comment]
@powder-river updated with commits from last night
https://github.com/gmhurley/movieratings

**Comment by gmhurley** [comment]
@powder-river IRT movie id... I get an ID by default. Shouldn't I be able to load the existing id into that ID?
