### ISSUE TITLE
22 -- Movie Lens Online -- Andrew Pierce

### ISSUE THREAD

**Issue by andrewmpierce** [tiyd-python-2015-08/assigments#311]
- [x] Night 1
  - [x] Miscellaneous
    - [x] Make commits after every significant change
    - [x] Use feature branches whenever you add something to a stable product
    - [x] Use requirements.txt and Django best practices for laying out your project
  - [x] Normal mode
    - [x] Create a Django project called movieratings
    - [x] Create a Django app inside your project
    - [x] Create models for users (raters), movies, and ratings
    - [x] Create Django admin pages for the models

**Comment by andrewmpierce** [comment]
Made some things.
https://github.com/andrewmpierce/Movie-Lens-Online

**Comment by powder-river** [comment]
@andrewmpierce so a few things. First you can't create a movie right now, it's blowing up so take a look at that error message. 

also, note that in your Rating model you create a rating and have a foreign key to a movie, but how do we know who gave it that rating????

**Comment by andrewmpierce** [comment]
@powder-river 
Fixed my night 1 stuff. Looks like it was a typo in my movie class. Should be good now.
