### ISSUE TITLE
01-- Fly-Your-Flag -- Karthik Kasala

### ISSUE THREAD

**Issue by kasalak** [tiyd-python-2015-08/assigments#32]
- [x] Code It
  - [x] Draw a flag with one or more turtles
- [x] Press the Issue
  - [x] Open a _WIP issue_ named `01 -- Fly Your Flag -- YOUR NAME`
  - [x] Put this task list in the description
  - [x] Check off the boxes as you complete items
  - [x] Add a comment with the _Share_ link to your flag
- [x] Hard Mode (optional)
  - [x] Move flag drawing code to a function
  - [x] Add a paramter to the function called size
  - [x] Test your flag drawing at various sizes to ensure it works

**Comment by kasalak** [comment]
Vietnamese flag: https://trinket.io/python/b23afab885

**Comment by kasalak** [comment]
Hardmode:

Indonesian flag: https://trinket.io/python/6fb704d039

**Comment by powder-river** [comment]
@kasalak good looking flags. I know we haven't covered this in class yet but remember functions from pre-work? How would your code look if you organized it in functions, for example

def draw_star()
    code
    code
    code

def draw_outline()
    code
    code
    code

what do you think this does for readabliity ?
