### ISSUE TITLE
01 -- Fly Your Flag -- Ryan Burton

### ISSUE THREAD

**Issue by rryanburton** [tiyd-python-2015-08/assigments#33]
- [x] Code It
  - [x] Draw a flag with one or more turtles
- [x] Press the Issue
  - [x] Open a _WIP issue_ named `01 -- Fly Your Flag -- YOUR NAME`
  - [x] Put this task list in the description
  - [x] Check off the boxes as you complete items
  - [x] Add a comment with the _Share_ link to your flag
- [ ] Hard Mode (optional)
  - [ ] Move flag drawing code to a function
  - [x] Add a paramter to the function called size
  - [x] Test your flag drawing at various sizes to ensure it works

**Comment by rryanburton** [comment]
https://trinket.io/python/45a407523b

Puerto Rico flag

**Comment by rryanburton** [comment]
submitted 
@jamesmallen 
@powder-river

**Comment by powder-river** [comment]
@rryanburton DAANNNGGG!!!!

**Comment by powder-river** [comment]
@rryanburton but seriously, really sharp looking flag and the code is really well organized. good use of functions to make the code more readable. Math is solid, user input instructions also on point. Well done!

**Comment by jmaroeder** [comment]
Great stuff!
