### ISSUE TITLE
01 --Fly-Your-Flag-- Bob Amand

### ISSUE THREAD

**Issue by BobAmand** [tiyd-python-2015-08/assigments#35]
- [x] Code It
  - [x] Draw a flag with one or more turtles
- [x] Press the Issue
  - [x] Open a _WIP issue_ named `01 -- Fly Your Flag -- YOUR NAME`
  - [x] Put this task list in the description
  - [x] Check off the boxes as you complete items
  - [x] Add a comment with the _Share_ link to your flag
- [x] Hard Mode (optional)
  - [x] Move flag drawing code to a function
  - [x] Add a paramter to the function called size
  - [x] Test your flag drawing at various sizes to ensure it works

**Comment by BobAmand** [comment]
https://trinket.io/library/trinkets/c9f5b4d013

Here is a trinket link to my flag code.  Attempted to build a loop to place stars across the flag with an offset; had to stop prior to success.  Also the size was parameterized but the stars do not re-size proportionately.

**Comment by powder-river** [comment]
@BobAmand good looking flag, good job overall. One of the things you'll find in coding, and in the class in particular is that there is more than one way to skin a cat. When we review HW tomorrow, be on the lookout for ways that you might be able to modify your code. Good Work!
