### ISSUE TITLE
02 -- Apple Tree Roots -- Glenn Hurley

### ISSUE THREAD

**Issue by gmhurley** [tiyd-python-2015-08/assigments#38]
- [x] Blank slate
  - [x] Create a GitHub repo called `approximate-square-root`
  - [x] Put a README.md file in the root of the repository describing what your program will do. (_feel free to start with the description above_)
  - [x] Make sure you commit your README.md file
- [x] Round fruit, square roots
  - [x] Create a blank file called square_root.py and commit it to your repo
  - [x] Have your program ask the user for a positive number and store it in a variable
  - [x] Have your program perform Newton's method of successive approximations to approximate the square root of the inputted number
- [x] Hard mode (optional)
  - [x] Each time through the loop, print out the number of iterations that have occurred
  - [x] Show an error message if the user enters any invalid input (negative number or non-numeric string)
- [x] Nightmare mode (optional)
  - [x] Allow negative numbers as input and display the result as a complex number
- [x] Submitting
  - [x] Make sure you commit and push your changes, and paste a link to the repo as a comment

**Comment by gmhurley** [comment]
https://github.com/gmhurley/approximate-square-root/tree/master

**Comment by gmhurley** [comment]
https://github.com/gmhurley/approximate-square-root/tree/hard-mode

**Comment by gmhurley** [comment]
https://github.com/gmhurley/approximate-square-root/tree/nightmare

Borrowed the abs() solution from @Shea-Wolfe for getting the negative square root.

**Comment by powder-river** [comment]
@ gmhurley well done glenn, well done. I would suggest that when you print out the iteration that you also print out the number associated with that iteration. keep up the good work!

**Comment by gmhurley** [comment]
@powder-river added the guess to the print out. TY for the feedback!
https://github.com/gmhurley/approximate-square-root/blob/nightmare/square_root.py

**Comment by powder-river** [comment]
@gmhurley no problem keep up the awesome work!
