### ISSUE TITLE
Apple Tree Roots

### ISSUE THREAD

**Issue by nckathleen** [tiyd-python-2015-08/assigments#41]
- [x] Blank slate
  - [x] Create a GitHub repo called `approximate-square-root`
  - [x] Put a README.md file in the root of the repository describing what your program will do. (_feel free to start with the description above_)
  - [x] Make sure you commit your README.md file
- [x] Round fruit, square roots
  - [x] Create a blank file called square_root.py and commit it to your repo
  - [x] Have your program ask the user for a positive number and store it in a variable
  - [x] Have your program perform Newton's method of successive approximations to approximate the square root of the inputted number
- [ ] Hard mode (optional)
  - [x] Each time through the loop, print out the number of iterations that have occurred
  - [ ] Show an error message if the user enters any invalid input (negative number or non-numeric string)
- [ ] Nightmare mode (optional)
  - [ ] Allow negative numbers as input and display the result as a complex number
- [x] Submitting
  - [x] Make sure you commit and push your changes, and paste a link to the repo as a comment

**Comment by nckathleen** [comment]
Here it is for normal mode.  I had already begun work on hard mode before I remembered to commit, so it's a but messy!
https://github.com/nckathleen/approximate-square-root/blob/master/square_root.py

**Comment by powder-river** [comment]
@nckathleen creative function names :) something to keep in mind. In general when we have  "production" ready code (in your case a HW submission) we generally delete commented out code. true comments are fine but code that has been commented out with no purpose should be deleted. Good job on the assignment

**Comment by nckathleen** [comment]
Cleaner output on this one, still normal mode:
https://github.com/nckathleen/approximate-square-root/blob/master/square_root.py
@powder-river @jamesmallen
