### ISSUE TITLE
02 --Apple Tree Roots -- Bob Amand

### ISSUE THREAD

**Issue by BobAmand** [tiyd-python-2015-08/assigments#42]
- [x] Blank slate
  - [x] Create a GitHub repo called `approximate-square-root`
  - [x] Put a README.md file in the root of the repository describing what your program will do. (_feel free to start with the description above_)
  - [x] Make sure you commit your README.md file
- [x] Round fruit, square roots
  - [x] Create a blank file called square_root.py and commit it to your repo
  - [x] Have your program ask the user for a positive number and store it in a variable
  - [x] Have your program perform Newton's method of successive approximations to approximate the square root of the inputted number
- [ ] Hard mode (optional)
  - [x] Each time through the loop, print out the number of iterations that have occurred
  - [ ] Show an error message if the user enters any invalid input (negative number or non-numeric string)
- [ ] Nightmare mode (optional)
  - [ ] Allow negative numbers as input and display the result as a complex number
- [x] Submitting
  - [x] Make sure you commit and push your changes, and paste a link to the repo as a comment

**Comment by BobAmand** [comment]
https://github.com/BobAmand/approximate-square-root

**Comment by BobAmand** [comment]
Submitted.  @powder-river @jamesmallen

**Comment by powder-river** [comment]
@BobAmand Bob! code turned out great! Think back to how when we fixed our naming conventions it lead to other bug fixes. that's just the tip of the iceberg when it comes to de-bugging good job!
