### ISSUE TITLE
02 -- Apple Tree Roots -- Andrew Pierce

### ISSUE THREAD

**Issue by andrewmpierce** [tiyd-python-2015-08/assigments#43]
- [x] Blank slate
  - [x] Create a GitHub repo called `approximate-square-root`
  - [x] Put a README.md file in the root of the repository describing what your program will do. (_feel free to start with the description above_)
  - [x] Make sure you commit your README.md file
- [x] Round fruit, square roots
  - [x] Create a blank file called square_root.py and commit it to your repo
  - [x] Have your program ask the user for a positive number and store it in a variable
  - [x] Have your program perform Newton's method of successive approximations to approximate the square root of the inputted number
- [x] Hard mode (optional)
  - [x] Each time through the loop, print out the number of iterations that have occurred
  - [x] Show an error message if the user enters any invalid input (negative number or non-numeric string)
- [ ] Nightmare mode (optional)
  - [ ] Allow negative numbers as input and display the result as a complex number
- [x] Submitting
  - [x] Make sure you commit and push your changes, and paste a link to the repo as a comment

**Comment by andrewmpierce** [comment]
Submitted
@jamesmallen 
@powder-river 
https://github.com/apierce1992/approximate-square-root (hard mode)

Playing with nightmare mode, we'll see how it goes.

**Comment by andrewmpierce** [comment]
Fixed the bug from hard mode. Submitting as normal while I tweak the bugs.
@jamesmallen 
@powder-river 
https://github.com/apierce1992/approximate-square-root (normal)

**Comment by powder-river** [comment]
@apierce1992 good work on the assignment. excellent use of the tools we talked about today. Work on the conditionals we talked about. let me know if you find your solution

**Comment by andrewmpierce** [comment]
@powder-river 
@jamesmallen 
I managed to get hard mode to work by implementing a try/except for the string values.
https://github.com/apierce1992/approximate-square-root
