### ISSUE TITLE
02 -- Apple Tree Roots -- Karthik Kasala

### ISSUE THREAD

**Issue by kasalak** [tiyd-python-2015-08/assigments#46]
- [x] Blank slate
  - [x] Create a GitHub repo called `approximate-square-root`
  - [x] Put a README.md file in the root of the repository describing what your program will do. (_feel free to start with the description above_)
  - [x] Make sure you commit your README.md file
- [x] Round fruit, square roots
  - [x] Create a blank file called square_root.py and commit it to your repo
  - [x] Have your program ask the user for a positive number and store it in a variable
  - [x] Have your program perform Newton's method of successive approximations to approximate the square root of the inputted number
- [ ] Hard mode (optional)
  - [ ] Each time through the loop, print out the number of iterations that have occurred
  - [ ] Show an error message if the user enters any invalid input (negative number or non-numeric string)
- [ ] Nightmare mode (optional)
  - [ ] Allow negative numbers as input and display the result as a complex number
- [x] Submitting
  - [x] Make sure you commit and push your changes, and paste a link to the repo as a comment

**Comment by kasalak** [comment]
Figured out 'git push' command was not working. Copied in my lines from atom, but will ask for clarification in/before class tomorrow, so I can fix

https://github.com/kasalak/approximate-square-root

@jamesmallen 
@powder-river

**Comment by powder-river** [comment]
@kasalak good work using minimal code. lets chat tomorrow if there are still git concerns. Git is a foreign idea to everyone here and it's important we have a solid foundation. Don't worry you're in a good spot, just let me know if you want to discuss git more after class tomorrow
