### ISSUE TITLE
02--Apple Tree Roots-- Michael Krawiec

### ISSUE THREAD

**Issue by msk007** [tiyd-python-2015-08/assigments#47]
- [x] Blank slate
  - [x] Create a GitHub repo called `approximate-square-root`
  - [x] Put a README.md file in the root of the repository describing what your program will do. (_feel free to start with the description above_)
  - [x] Make sure you commit your README.md file
- [x] Round fruit, square roots
  - [x] Create a blank file called square_root.py and commit it to your repo
  - [x] Have your program ask the user for a positive number and store it in a variable
  - [x] Have your program perform Newton's method of successive approximations to approximate the square root of the inputted number
- [ ] Hard mode (optional)
  - [x] Each time through the loop, print out the number of iterations that have occurred
  - [ ] Show an error message if the user enters any invalid input (negative number or non-numeric string)
- [ ] Nightmare mode (optional)
  - [ ] Allow negative numbers as input and display the result as a complex number
- [x] Submitting
  - [x] Make sure you commit and push your changes, and paste a link to the repo as a comment

**Comment by msk007** [comment]
this is what i came up with.i had a hard time adding it to git. had to create a new repository because things got messed up somehow.I just got confused. My daughter can ride the bus now so i'll be around all day for lab to get loose ends i'm having issues with squared away.

https://github.com/msk007/approximate-square-root2/blob/master/square_root.py

SUBMIT
@powder-river 
@jamesmallen

**Comment by msk007** [comment]
this is what i came up with.i had a hard time adding it to git. had to create a new repository because things got messed up somehow.I just got confused. My daughter can ride the bus now so i'll be around all day for lab to get loose ends i'm having issues with squared away.

https://github.com/msk007/approximate-square-root2/blob/master/square_root.py

SUBMIT
@powder-river
@jamesmallen

**Comment by powder-river** [comment]
@msk007 so your submission returned this
SyntaxError: EOF while scanning triple-quoted string literal
can you tell me why?

(i fixed it and am looking at that but I want you to find the bug)

**Comment by powder-river** [comment]
@msk007 also take a look at this code 
def user_input():
    if (number == 0) then
    my_sqrt=0
    if (number < 0) then
    print ("Invalid Number")
    if (number > 0) then
    my_sqrt()

it makes sense in "english", why doesn't it make sense in python?

**Comment by powder-river** [comment]
@msk007 let's talk today, the code needs some work with formatting which we can go through together, but I had to make a lot of corrections to attempt to run it which at this early stage in the game but we will quickly get to the point where doing that is not so simple, let's talk about this more today so we can make corrections
