### ISSUE TITLE
01--Fly-Your-Flag -- Brent Hilsabeck

### ISSUE THREAD

**Issue by ghost** [tiyd-python-2015-08/assigments#49]
- [x] Code It
  - [x] Draw a flag with one or more turtles
- [x] Press the Issue
  - [x] Open a _WIP issue_ named `01 -- Fly Your Flag -- YOUR NAME`
  - [x] Put this task list in the description
  - [x] Check off the boxes as you complete items
  - [x] Add a comment with the _Share_ link to your flag
- [x] Hard Mode (optional)
  - [x] Move flag drawing code to a function
  - [x] Add a paramter to the function called size
  - [x] Test your flag drawing at various sizes to ensure it works

**Comment by ghost** [comment]
@jamesmallen 
@powder-river 

https://trinket.io/library/trinkets/6e012a021c

**Comment by powder-river** [comment]
@bhilsabeck great flag code is well organized. good use of comments to increase readability. A thought. what happens when your prompt asks for a number and I type in "potato" What can be done about this?
