### ISSUE TITLE
04 -- Frequency Filer -- Glenn Hurley

### ISSUE THREAD

**Issue by gmhurley** [tiyd-python-2015-08/assigments#51]
- [x] Blank slate
  - [x] Create a GitHub repo called `frequency-filer`
  - [x] Put a `README.md` file in it and copy word_frequency.py, word_frequency_test.py, and sample.txt from this repository into it.
- [x] Normal Mode
  - [x] Open `sample.txt` and read in the text
  - [x] Count the number of times each word is used, regardless of capitalization
  - [x] Find the top 20 words used and output them and their frequency to stdout
  - [x] Run word_frequency_test.py and ensure you pass all the tests
- [x] Hard Mode (optional)
  - [x] Add a list of ignored words and don't count these in the word frequencies
  - [x] Make your program take the name of the file to read on the command line, so it doesn't just have to work with `sample.txt`.
- [x] Nightmare Mode (optional)
  - [x] Output the top 20 words' frequencies using a simple text-based histogram
  - [x] Normalize the histogram so there are never more than 50 `#` marks.

**Comment by gmhurley** [comment]
https://github.com/gmhurley/frequency-filer/tree/normal_mode
@jamesmallen 
@powder-river

**Comment by gmhurley** [comment]
https://github.com/gmhurley/frequency-filer/tree/hard_mode
@jamesmallen 
@powder-river

**Comment by powder-river** [comment]
@gmhurley tell your TA to learn how to look at code and you'll get this feedback sooner. well done on hard road. good naming conventions and Readme as well glenn.

**Comment by gmhurley** [comment]
@powder-river getting close on nightmare... stand by ;)

**Comment by gmhurley** [comment]
@powder-river well... never mind on getting close... stuck on tuple assignment =0

**Comment by gmhurley** [comment]
https://github.com/gmhurley/frequency-filer/tree/nightmare_mode
@jamesmallen @powder-river
