### ISSUE TITLE
02 -- Apple Tree Roots -- Ryan Burton

### ISSUE THREAD

**Issue by rryanburton** [tiyd-python-2015-08/assigments#52]
- [x] Blank slate
  - [x] Create a GitHub repo called `approximate-square-root`
  - [x] Put a README.md file in the root of the repository describing what your program will do. (_feel free to start with the description above_)
  - [x] Make sure you commit your README.md file
- [x] Round fruit, square roots
  - [x] Create a blank file called square_root.py and commit it to your repo
  - [x] Have your program ask the user for a positive number and store it in a variable
  - [x] Have your program perform Newton's method of successive approximations to approximate the square root of the inputted number
- [ ] Hard mode (optional)
  - [ ] Each time through the loop, print out the number of iterations that have occurred
  - [ ] Show an error message if the user enters any invalid input (negative number or non-numeric string)
- [ ] Nightmare mode (optional)
  - [ ] Allow negative numbers as input and display the result as a complex number
- [x] Submitting
  - [x] Make sure you commit and push your changes, and paste a link to the repo as a comment

**Comment by rryanburton** [comment]
https://github.com/rryanburton/approximate-square-root

1 example in long/manual form
1 example using a while loop, still having issues making the entire process a function that works when inputting newton_method(#) and getting same output, reviewing notes on functions now to figure it out. -RB

@jamesmallen 
@powder-river

**Comment by powder-river** [comment]
@rryanburton the code is good, it transformed good from where you had it. think about how you might end the loop without a counter? you'll see some ways your classmates approached it differently. good job overall, let's plan on talking more tomorrow on how to start a project and how to refactor
