### ISSUE TITLE
04 -- Frequency-Filer - David Denney

### ISSUE THREAD

**Issue by ghost** [tiyd-python-2015-08/assigments#53]
- [x] Blank slate
  - [x] Create a GitHub repo called `frequency-filer`
  - [x] Put a `README.md` file in it and copy word_frequency.py, word_frequency_test.py, and sample.txt from this repository into it.
- [x] Normal Mode
  - [x] Open `sample.txt` and read in the text
  - [x] Count the number of times each word is used, regardless of capitalization
  - [x] Find the top 20 words used and output them and their frequency to stdout
  - [x] Run word_frequency_test.py and ensure you pass all the tests
- [ ] Hard Mode (optional)
  - [ ] Add a list of ignored words and don't count these in the word frequencies
  - [ ] Make your program take the name of the file to read on the command line, so it doesn't just have to work with `sample.txt`.
- [ ] Nightmare Mode (optional)
  - [ ] Output the top 20 words' frequencies using a simple text-based histogram
  - [ ] Normalize the histogram so there are never more than 50 `#` marks.

**Comment by ghost** [comment]
https://github.com/ddenney/frequency-flier/blob/master/word_frequency.py

**Comment by ghost** [comment]
SUBMITTED 

@jamesmallen 
@powder-river

**Comment by powder-river** [comment]
@jamesmallen @ddenney tests pass but there are the main file produces no output, let me know if you find a solution

**Comment by jmaroeder** [comment]
Looks like it's a spacing/indentation issue - it might have happened from copying over your code from a Notebook. Please fix the spacing, check your output, and resubmit!

**Comment by powder-river** [comment]
@ddenney revisions looking good! label has been changed to reflect your fixes
