### ISSUE TITLE
03 -- Palindromic -- Will Butts

### ISSUE THREAD

**Issue by Shea-Wolfe** [tiyd-python-2015-08/assigments#57]
- [x] Blank slate
  - [x] Create a GitHub repo called `palindromic`
  - [x] Put a `README.md` file in it and copy palindrome.py and palindrome_test.py from this repository into it.
- [x] Normal Mode
  - [x] Write your `main()` function to ask the user for a word/sentence, pass it into the is_palindrome function, and state whether or not the the sentence is palindromic
  - [x] Write your `is_palindrome` function **using recursion**
  - [x] Run palindrome_test.py and ensure you pass all the tests
- [x] Hard Mode (optional)
  - [x] Make an iterative version of your `is_palindrome` function (using loops instead of recursion), and ensure it passes the tests too

**Comment by Shea-Wolfe** [comment]
@jamesmallen @powder-river 

https://github.com/Shea-Wolfe/Palindromic

**Comment by powder-river** [comment]
@Shea-Wolfe  good looking code Will, well done!  We're going to talk more about Readme's today, it looks like your code is meant to be commented and commented in other to run different approaches. If that is the case the Readme should reflect that. Good job!
