### ISSUE TITLE
03 -- Frequency Filer -- Tyler Kotkin

### ISSUE THREAD

**Issue by TylerKotkin** [tiyd-python-2015-08/assigments#58]
- [x] Blank slate
  - [x] Create a GitHub repo called `palindromic`
  - [x] Put a `README.md` file in it and copy palindrome.py and palindrome_test.py from this repository into it.
- [x] Normal Mode
  - [x] Write your `main()` function to ask the user for a word/sentence, pass it into the is_palindrome function, and state whether or not the the sentence is palindromic
  - [x] Write your `is_palindrome` function **using recursion**
  - [x] Run palindrome_test.py and ensure you pass all the tests
- [ ] Hard Mode (optional)
  - [ ] Make an iterative version of your `is_palindrome` function (using loops instead of recursion), and ensure it passes the tests too

**Comment by TylerKotkin** [comment]
https://github.com/TylerKotkin/palindromic

submitted

@jamesmallen 
@powder-river

**Comment by powder-river** [comment]
@TylerKotkin good lean looking code, smart use of regex as well.
