### ISSUE TITLE
03 - palindromes - Andrew Pierce

### ISSUE THREAD

**Issue by andrewmpierce** [tiyd-python-2015-08/assigments#59]
- [x] Blank slate
  - [x] Create a GitHub repo called `palindromic`
  - [x] Put a `README.md` file in it and copy palindrome.py and palindrome_test.py from this repository into it.
- [x] Normal Mode
  - [x] Write your `main()` function to ask the user for a word/sentence, pass it into the is_palindrome function, and state whether or not the the sentence is palindromic
  - [x] Write your `is_palindrome` function **using recursion**
  - [x] Run palindrome_test.py and ensure you pass all the tests
- [x] Hard Mode (optional)
  - [x] Make an iterative version of your `is_palindrome` function (using loops instead of recursion), and ensure it passes the tests too

**Comment by andrewmpierce** [comment]
Submitted
@jamesmallen 
@powder-river 
https://github.com/apierce1992/palindrome (hard mode)
Note that the palindrome_test.py currently points to the hard mode version. palindrome_hard.py

**Comment by powder-river** [comment]
@apierce1992 solid submission, keep in mind the readme should give directions of how to use the program as well as a detailed description of what it does. keep that in mind for your next project.good work!
