### ISSUE TITLE
03 -- Palindromic -- Jonathan Frederick

### ISSUE THREAD

**Issue by JonathanFrederick** [tiyd-python-2015-08/assigments#61]
- [x] Blank slate
  - [x] Create a GitHub repo called `palindromic`
  - [x] Put a `README.md` file in it and copy palindrome.py and palindrome_test.py from this repository into it.
- [x] Normal Mode
  - [x] Write your `main()` function to ask the user for a word/sentence, pass it into the is_palindrome function, and state whether or not the the sentence is palindromic
  - [x] Write your `is_palindrome` function **using recursion**
  - [x] Run palindrome_test.py and ensure you pass all the tests
- [x] Hard Mode (optional)
  - [x] Make an iterative version of your `is_palindrome` function (using loops instead of recursion), and ensure it passes the tests too

**Comment by JonathanFrederick** [comment]
https://github.com/JonathanFrederick/palindromic

**Comment by JonathanFrederick** [comment]
SUBMITTED
@jamesmallen @powder-river

**Comment by powder-river** [comment]
@JonathanFrederick sorry I forgot to comment last night. We haven't talked about Readme conventions yet but it looks like you commented out one method of running your code and is meant to be uncommented if I want to use that method. If that is the case you want to state that in the Readme. We will talk about it more later today. Great Code!
