### ISSUE TITLE
03 -- Palindromic -- Ryan Burton

### ISSUE THREAD

**Issue by rryanburton** [tiyd-python-2015-08/assigments#63]
- [x] Blank slate
  - [x] Create a GitHub repo called `palindromic`
  - [x] Put a `README.md` file in it and copy palindrome.py and palindrome_test.py from this repository into it.
- [x] Normal Mode
  - [x] Write your `main()` function to ask the user for a word/sentence, pass it into the is_palindrome function, and state whether or not the the sentence is palindromic
  - [x] Write your `is_palindrome` function **using recursion**
  - [x] Run palindrome_test.py and ensure you pass all the tests
- [ ] Hard Mode (optional)
  - [ ] Make an iterative version of your `is_palindrome` function (using loops instead of recursion), and ensure it passes the tests too

**Comment by rryanburton** [comment]
https://github.com/rryanburton/palindromic

@jamesmallen 
@powder-river

**Comment by powder-river** [comment]
@rryanburton good work on the HW the recursive functions could have been more successful but your loop functions were spot on. I know that getting your mind around recursive functions is a difficult task.
