### ISSUE TITLE
03 - Palindromic - Kathleen Rauh

### ISSUE THREAD

**Issue by nckathleen** [tiyd-python-2015-08/assigments#64]
- [x] Blank slate
  - [x] Create a GitHub repo called `palindromic`
  - [x] Put a `README.md` file in it and copy palindrome.py and palindrome_test.py from this repository into it.
- [x] Normal Mode
  - [x] Write your `main()` function to ask the user for a word/sentence, pass it into the is_palindrome function, and state whether or not the the sentence is palindromic
  - [x] Write your `is_palindrome` function **using recursion**
  - [x] Run palindrome_test.py and ensure you pass all the tests
- [ ] Hard Mode (optional)
  - [ ] Make an iterative version of your `is_palindrome` function (using loops instead of recursion), and ensure it passes the tests too

**Comment by nckathleen** [comment]
Normal mode
@powder-river @jamesmallen 
https://github.com/nckathleen/palindromic

**Comment by powder-river** [comment]
@nckathleen looks like your recursion is working as intended with all your tests passing, good work
