### ISSUE TITLE
03 -- Palindromic -- Glenn Hurley

### ISSUE THREAD

**Issue by gmhurley** [tiyd-python-2015-08/assigments#65]
- [x] Blank slate
  - [x] Create a GitHub repo called `palindromic`
  - [x] Put a `README.md` file in it and copy palindrome.py and palindrome_test.py from this repository into it.
- [x] Normal Mode
  - [x] Write your `main()` function to ask the user for a word/sentence, pass it into the is_palindrome function, and state whether or not the the sentence is palindromic
  - [x] Write your `is_palindrome` function **using recursion**
  - [x] Run palindrome_test.py and ensure you pass all the tests
- [x] Hard Mode (optional)
  - [x] Make an iterative version of your `is_palindrome` function (using loops instead of recursion), and ensure it passes the tests too

**Comment by gmhurley** [comment]
Did the for loop first by accident:
https://github.com/gmhurley/palindromic/tree/master

**Comment by gmhurley** [comment]
This felt dirty the way I had to use the returns... but it worked:
https://github.com/gmhurley/palindromic/tree/recursion

**Comment by powder-river** [comment]
@gmhurley lol good description. We call this phenomenon of "feeling dirty" code smell. Basically it means we have a feeling there is a better and/or simpler way to do things. From a production standpoint the code works and it satisfies the requirements of the HW. If you want to refactor find James or Myself and we can talk about that.
