### ISSUE TITLE
03 -- Palindromic - David Denney

### ISSUE THREAD

**Issue by ghost** [tiyd-python-2015-08/assigments#66]
- [x] Blank slate
  - [x] Create a GitHub repo called `palindromic`
  - [x] Put a `README.md` file in it and copy palindrome.py and palindrome_test.py from this repository into it.
- [x] Normal Mode
  - [x] Write your `main()` function to ask the user for a word/sentence, pass it into the is_palindrome function, and state whether or not the the sentence is palindromic
  - [x] Write your `is_palindrome` function **using recursion**
  - [x] Run palindrome_test.py and ensure you pass all the tests
- [x] Hard Mode (optional)
  - [x] Make an iterative version of your `is_palindrome` function (using loops instead of recursion), and ensure it passes the tests too

**Comment by ghost** [comment]
Normal Mode: https://github.com/ddenney/palindromic/tree/recursion

**Comment by ghost** [comment]
Hard Mode: https://github.com/ddenney/palindromic/tree/master

**Comment by ghost** [comment]
SUMBITTED 

@jamesmallen 
@powder-river

**Comment by powder-river** [comment]
@ddenney let's talk during lab today, I can see you made a solid attempt at the assignment, but it looks like nothing is running.

**Comment by ghost** [comment]
@powder-river That's strange. It all ran successfully yesterday. I had some issues pushing to git so the wrong code may be there.
