### ISSUE TITLE
03 -- Palindromic -- Adam Hartz

### ISSUE THREAD

**Issue by ahartz1** [tiyd-python-2015-08/assigments#68]
- [x] Blank slate
  - [x] Create a GitHub repo called `palindromic`
  - [x] Put a `README.md` file in it and copy palindrome.py and palindrome_test.py from this repository into it.
- [x] Normal Mode
  - [x] Write your `main()` function to ask the user for a word/sentence, pass it into the is_palindrome function, and state whether or not the the sentence is palindromic
  - [x] Write your `is_palindrome` function **using recursion**
  - [x] Run palindrome_test.py and ensure you pass all the tests
- [x] Hard Mode (optional)
  - [x] Make an iterative version of your `is_palindrome` function (using loops instead of recursion), and ensure it passes the tests too

**Comment by ahartz1** [comment]
https://github.com/ahartz1/palindromic
@jamesmallen 
@powder-river 

My own tests confirm that the non-palindromes are being successfully identified, but I can't seem to get them to pass the test's non-palindrome assertion.

**Comment by powder-river** [comment]
@ahartz1 passing tests can be tricky, and considering we  haven't talked about tests yet good work. I'm glad to see the changes you made after doing the refactoring that we had talked about were successful. well done

**Comment by ahartz1** [comment]
Finally, everything is working as it should for both the recursive and iterative solutions.
