### ISSUE TITLE
03 -- Palindromic -- Karthik Kasala

### ISSUE THREAD

**Issue by kasalak** [tiyd-python-2015-08/assigments#69]
- [x] Blank slate
  - [x] Create a GitHub repo called `palindromic`
  - [x] Put a `README.md` file in it and copy palindrome.py and palindrome_test.py from this repository into it.
- [x] Normal Mode
  - [x] Write your `main()` function to ask the user for a word/sentence, pass it into the is_palindrome function, and state whether or not the the sentence is palindromic
  - [x] Write your `is_palindrome` function **using recursion**
  - [x] Run palindrome_test.py and ensure you pass all the tests
- [ ] Hard Mode (optional)
  - [ ] Make an iterative version of your `is_palindrome` function (using loops instead of recursion), and ensure it passes the tests too

**Comment by kasalak** [comment]
https://github.com/kasalak/palindromic

@powder-river 
@jamesmallen

**Comment by powder-river** [comment]
@kasalak good looking code, as I mentioned to your classmates(and I fall into this category as well) the directions do technically say you are supposed to write your `is_pandindrome` function using recursion. Just make sure you understand the concept using recursion. really good job though. from a functionality standpoint all looks good!
