### ISSUE TITLE
00 -- Ready Steady Go -- Glenn Hurley

### ISSUE THREAD

**Issue by gmhurley** [tiyd-python-2015-08/assigments#7]
- [x] **GitHubbing to know you**
  - [x] [Create a GitHub account](https://github.com/signup)
  - [x] Find and star [the assignments repository](https://github.com/tiyd-python-2015-08/assigments)
  - [x] [Edit your GitHub profile](https://github.com/settings/profile) to provide:
    - [x] A picture, so we can recognize your face.
    - [x] Your full name, so we can recognize your name.
    - [x] A valid public email address, so we can contact you.
- [x] **You've Got Issues**
  - [x] [Create a new _WIP Issue_](https://github.com/tiyd-python-2015-08/assigments/issues/new)
  - [x] Name it `00 -- Ready Steady Go -- YOUR NAME` (where `YOUR NAME` is _your_ name)
  - [x] Make this checklist the description
  - [x] Start checking off boxes :astonished:
- [x] **Brewmaster**
  - [x] [Install Homebrew](http://brew.sh) on your Mac
    - [x] Open `Terminal.app`; Don't Panic.
    - [x] [Install Homebrew and the `brew` command](http://brew.sh/#install)
    - [x] Read (or at least skim) [the Homebrew Wiki](https://github.com/Homebrew/homebrew/tree/master/share/doc/homebrew#readme) to learn more about Homebrew
  - [x] Using the `brew` command, install the following packages:
    - [x] `readline`
    - [x] `git`
    - [x] `python3`
    - [x] `direnv`
    - [x] `tree`
    - [x] `wget`
    - [x] `trash`
    - [x] `bash-completion`
  - [x] Install pip and virtualenv by running the following commands:
    - [x] `sudo easy_install pip`
    - [x] `sudo pip install virtualenv`
  - [x] Install some helpful dotfiles with the following commands:
    - [x] `cd ~`
    - [x] `git clone https://github.com/tiyd-python-2015-08/dotfiles.git`
    - [x] `./dotfiles/bin/dfm install`
    - [x] Close your terminal window and re-open it - you should get a different command prompt!
  - [x] Add the output of the following command as comments on your _WIP Issue_:
    - [x] `which git && git --version`
    - [x] `which python3 && python3 --version`
  - [x] Install the following (bonus if you use `brew`):
    - [x] [Google Chrome](http://google.com/chrome)
    - [x] [Atom](http://atom.io)
    - [x] [Slack](http://www.slack.com)
- [x] **Send all my GitHub to you...**
  - [x] [Complete the "Hello World" GitHub guide](https://guides.github.com/activities/hello-world/)
  - [x] Add a link to your new GitHub repo as a comment on your _WIP Issue_
  - [x] [Complete the "Forking Projects" GitHub guide](https://guides.github.com/activities/forking/)
  - [x] Add a link to your forked `Spoon-Kinfe` repo as a comment on your _WIP Issue_

**Comment by gmhurley** [comment]
/usr/bin/git
git version 2.3.2 (Apple Git-55)

**Comment by gmhurley** [comment]
/Library/Frameworks/Python.framework/Versions/3.4/bin/python3
Python 3.4.1

**Comment by gmhurley** [comment]
https://github.com/gmhurley/hello-world

**Comment by gmhurley** [comment]
https://github.com/gmhurley/Spoon-Knife

**Comment by jmaroeder** [comment]
Can you cd into a folder that has been set up with an .envrc file and paste the output of `which python` when you run it inside that folder? It looks like your system python has been replaced with something from python.org

**Comment by gmhurley** [comment]
(tiy)Glenns-MacBook-Pro:~/tiy/week1$ ls
total 64
drwxr-xr-x  9 glennhurley  staff   306B Aug 31 15:13 .
drwxr-xr-x  5 glennhurley  staff   170B Aug 31 15:13 ..
-rw-r--r--  1 glennhurley  staff    30B Aug 31 11:48 .envrc
drwxr-xr-x  3 glennhurley  staff   102B Aug 31 12:03 .ipynb_checkpoints
drwxr-xr-x  6 glennhurley  staff   204B Aug 31 14:08 Spoon-Knife
drwxr-xr-x  3 glennhurley  staff   102B Aug 31 14:35 **pycache**
-rw-r--r--  1 glennhurley  staff   340B Aug 31 15:08 test_draw.py
drwxr-xr-x  5 glennhurley  staff   170B Aug 31 16:39 turtle_flag
-rw-r--r--  1 glennhurley  staff    20K Aug 31 12:08 w1d1.ipynb
(tiy)Glenns-MacBook-Pro:~/tiy/week1$ which python
/Users/glennhurley/.virtualenvs/tiy/bin/python

**Comment by jmaroeder** [comment]
It looks like the directory is just set up with virtualenv, not with direnv... we can take a look at it during lab time tomorrow if you'd like to get on the same setup as me, or if you're comfortable with it working this way that's fine with me.
