### ISSUE TITLE
05 -- Mystery Word - David Denney

### ISSUE THREAD

**Issue by ghost** [tiyd-python-2015-08/assigments#73]
- [x] Blank slate
  - [x] Create a GitHub repo called `mystery-word`
  - [x] Put a `README.md` file in it and copy mystery_word.py and mystery_word_test.py from this repository into it.
- [x] Normal Mode
  - [x] Load words from `/usr/share/dict/words`
  - [x] Write functions to select a subset of the complete word list
  - [x] Write a function to select a word at random from the word list
  - [x] Write a function to display a word with blanks/letters filled in the appropriate spots
  - [x] Write a function to check if a word has been completely guessed
  - [x] Write other helper functions as necessary to help with the flow of the game
  - [x] Run mystery_word_test.py and ensure you pass all the tests
- [ ] Hard Mode (optional)
  - [ ] Implement the evil version of the game and put it in evil_mystery_word.py
  - [ ] Write tests and put them in evil_mystery_word_tests.py

**Comment by ghost** [comment]
SUBMITTED 

@jamesmallen 
@powder-river

**Comment by ghost** [comment]
https://github.com/ddenney/mystery-word/blob/master/mystery_word.py

**Comment by powder-river** [comment]
@ddenney good submission denny, Strong readme as well. The only issue i saw is when the came was over I wanted to quit, i typed in no and it started the game over again.
