### ISSUE TITLE
04 -- Frequency Filer -- Andrew Pierce

### ISSUE THREAD

**Issue by andrewmpierce** [tiyd-python-2015-08/assigments#75]
- [x] Blank slate
  - [x] Create a GitHub repo called `frequency-filer`
  - [x] Put a `README.md` file in it and copy word_frequency.py, word_frequency_test.py, and sample.txt from this repository into it.
- [x] Normal Mode
  - [x] Open `sample.txt` and read in the text
  - [x] Count the number of times each word is used, regardless of capitalization
  - [x] Find the top 20 words used and output them and their frequency to stdout
  - [x] Run word_frequency_test.py and ensure you pass all the tests
- [x] Hard Mode (optional)
  - [x] Add a list of ignored words and don't count these in the word frequencies
  - [x] Make your program take the name of the file to read on the command line, so it doesn't just have to work with `sample.txt`.
- [x] Nightmare Mode (optional)
  - [x] Output the top 20 words' frequencies using a simple text-based histogram
  - [x] Normalize the histogram so there are never more than 50 `#` marks.

**Comment by andrewmpierce** [comment]
Submitted! Works as hard mode or reg or nightmare, but test is pointed at frequency_filer_hard.py
@jamesmallen 
@powder-river 
https://github.com/apierce1992/frequency-filer

**Comment by powder-river** [comment]
@apierce1992 great code man. looking good on all fronts, well done appreciate you taking in naming conventions and readme, style as we discussed yesterday
