### ISSUE TITLE
04 -- Frequency Filer -- Tyler Kotkin

### ISSUE THREAD

**Issue by TylerKotkin** [tiyd-python-2015-08/assigments#76]
- [x] Blank slate
  - [x] Create a GitHub repo called `frequency-filer`
  - [x] Put a `README.md` file in it and copy word_frequency.py, word_frequency_test.py, and sample.txt from this repository into it.
- [x] Normal Mode
  - [x] Open `sample.txt` and read in the text
  - [x] Count the number of times each word is used, regardless of capitalization
  - [x] Find the top 20 words used and output them and their frequency to stdout
  - [x] Run word_frequency_test.py and ensure you pass all the tests
- [ ] Hard Mode (optional)
  - [ ] Add a list of ignored words and don't count these in the word frequencies
  - [ ] Make your program take the name of the file to read on the command line, so it doesn't just have to work with `sample.txt`.
- [ ] Nightmare Mode (optional)
  - [ ] Output the top 20 words' frequencies using a simple text-based histogram
  - [ ] Normalize the histogram so there are never more than 50 `#` marks.

**Comment by TylerKotkin** [comment]
https://github.com/TylerKotkin/frequency-filer

@jamesmallen 
@powder-river

**Comment by powder-river** [comment]
code is looking awesome @TylerKotkin  I'm glad you took in the concept of re-assigning a variable as opposed to var1 var2 var3 etc. see what kind of markdown syntax you can use to make your readme look even sharper. well done
