### ISSUE TITLE
04 -- Frequency-Filer  -- Ryan Burton

### ISSUE THREAD

**Issue by rryanburton** [tiyd-python-2015-08/assigments#77]
- [x] Blank slate
  - [x] Create a GitHub repo called `frequency-filer`
  - [x] Put a `README.md` file in it and copy word_frequency.py, word_frequency_test.py, and sample.txt from this repository into it.
- [ ] Normal Mode
  - [x] Open `sample.txt` and read in the text
  - [x] Count the number of times each word is used, regardless of capitalization
  - [x] Find the top 20 words used and output them and their frequency to stdout
  - [ ] Run word_frequency_test.py and ensure you pass all the tests
- [ ] Hard Mode (optional)
  - [x] Add a list of ignored words and don't count these in the word frequencies
  - [ ] Make your program take the name of the file to read on the command line, so it doesn't just have to work with `sample.txt`.
- [ ] Nightmare Mode (optional)
  - [ ] Output the top 20 words' frequencies using a simple text-based histogram
  - [ ] Normalize the histogram so there are never more than 50 `#` marks.

**Comment by rryanburton** [comment]
https://github.com/rryanburton/frequency-filer

@jamesmallen 
@powder-river 

i'm disappointed that i was able to almost get what i was after. at some point tonight i had a list that looked like what we were supposed to get, but i didn't use a dictionary, so i went back in and tried to make it work with a dict and functions, but at that point i was getting errors and went around in circles unable to make anything happen. by the end i had no idea wtf was happening with any of it.

**Comment by powder-river** [comment]
@rryanburton you have good ideas and you do have a basic structure. the tests don't pass, and it's not pretty. I would say you have enough for yellow. You're almost there, a couple more lines of code and you should have it. Make sure you listen to what @jamesmallen has to say about run times
