### ISSUE TITLE
04 -- Frequent Filer -- Jonathan Frederick

### ISSUE THREAD

**Issue by JonathanFrederick** [tiyd-python-2015-08/assigments#78]
- [x] Blank slate
  - [x] Create a GitHub repo called `frequency-filer`
  - [x] Put a `README.md` file in it and copy word_frequency.py, word_frequency_test.py, and sample.txt from this repository into it.
- [x] Normal Mode
  - [x] Open `sample.txt` and read in the text
  - [x] Count the number of times each word is used, regardless of capitalization
  - [x] Find the top 20 words used and output them and their frequency to stdout
  - [x] Run word_frequency_test.py and ensure you pass all the tests
- [ ] Hard Mode (optional)
  - [ ] Add a list of ignored words and don't count these in the word frequencies
  - [ ] Make your program take the name of the file to read on the command line, so it doesn't just have to work with `sample.txt`.
- [ ] Nightmare Mode (optional)
  - [ ] Output the top 20 words' frequencies using a simple text-based histogram
  - [ ] Normalize the histogram so there are never more than 50 `#` marks.

**Comment by JonathanFrederick** [comment]
https://github.com/JonathanFrederick/frequency-filer

**Comment by JonathanFrederick** [comment]
Submitted, but I still want to get back to Hard Mode and Nightmare Mode at some point
@jamesmallen @powder-river

**Comment by jmaroeder** [comment]
Great stuff! Did you test the apostrophe stuff that you encoded in your regex?

**Comment by JonathanFrederick** [comment]
@jamesmallen I tucked a "can't" at the end of the sample.txt for a bit and that seemed to work
