### ISSUE TITLE
04 -- Frequency Filer -- Adam Hartz

### ISSUE THREAD

**Issue by ahartz1** [tiyd-python-2015-08/assigments#79]
- [x] Blank slate
  - [x] Create a GitHub repo called `frequency-filer`
  - [x] Put a `README.md` file in it and copy word_frequency.py, word_frequency_test.py, and sample.txt from this repository into it.
- [x] Normal Mode
  - [x] Open `sample.txt` and read in the text
  - [x] Count the number of times each word is used, regardless of capitalization
  - [x] Find the top 20 words used and output them and their frequency to stdout
  - [x] Run word_frequency_test.py and ensure you pass all the tests
- [x] Hard Mode (optional)
  - [x] Add a list of ignored words and don't count these in the word frequencies
  - [x] Make your program take the name of the file to read on the command line, so it doesn't just have to work with `sample.txt`.
- [ ] Nightmare Mode (optional)
  - [ ] Output the top 20 words' frequencies using a simple text-based histogram
  - [ ] Normalize the histogram so there are never more than 50 `#` marks.

**Comment by ahartz1** [comment]
Normal Mode in master branch.

https://github.com/ahartz1/frequency-filer
SUBMIT
@powder-river @jamesmallen

**Comment by ahartz1** [comment]
Hard Mode working in master.

**Comment by powder-river** [comment]
@jamesmallen @ahartz1  test pass but program doesn't run. let me know when you make the fix

`Traceback (most recent call last):
  File "word_frequency.py", line 73, in <module>
    main()
  File "word_frequency.py", line 65, in main
    with open(sys.argv[1]) as f:
IndexError: list index out of range`

**Comment by jmaroeder** [comment]
@ahartz1 : if your program requires command-line arguments, make sure you include some helpful output if the user tries to run your program without command-line arguments! It would also be a good idea to include notes about how to run the program in the README file.

**Comment by ahartz1** [comment]
I've fixed the problem and updated my README.
@jamesmallen @powder-river

**Comment by powder-river** [comment]
@ahartz1 good fix and README update, your color status has been changed to reflect your status. good job!
