### ISSUE TITLE
04 -- Frequency Filer -- Kathleen Rauh

### ISSUE THREAD

**Issue by nckathleen** [tiyd-python-2015-08/assigments#80]
- [x] Blank slate
  - [x] Create a GitHub repo called `frequency-filer`
  - [x] Put a `README.md` file in it and copy word_frequency.py, word_frequency_test.py, and sample.txt from this repository into it.
- [ ] Normal Mode
  - [x] Open `sample.txt` and read in the text
  - [x] Count the number of times each word is used, regardless of capitalization
  - [ ] Find the top 20 words used and output them and their frequency to stdout
  - [ ] Run word_frequency_test.py and ensure you pass all the tests
- [ ] Hard Mode (optional)
  - [ ] Add a list of ignored words and don't count these in the word frequencies
  - [ ] Make your program take the name of the file to read on the command line, so it doesn't just have to work with `sample.txt`.
- [ ] Nightmare Mode (optional)
  - [ ] Output the top 20 words' frequencies using a simple text-based histogram
  - [ ] Normalize the histogram so there are never more than 50 `#` marks.

**Comment by nckathleen** [comment]
Added steps checklist for project.

**Comment by nckathleen** [comment]
https://github.com/nckathleen/Frequency-filer/commit/3c567e57492672aea32d1933314028c3ecc98583
Not yet ready for testing.
@jamesmallen @powder-river

**Comment by powder-river** [comment]
@jamesmallen @nckathleen we should talk about your code today, hit me up after huddles
