### ISSUE TITLE
04--Frequency Filer--Karthik Kasala

### ISSUE THREAD

**Issue by kasalak** [tiyd-python-2015-08/assigments#81]
- [x] Blank slate
  - [x] Create a GitHub repo called `frequency-filer`
  - [x] Put a `README.md` file in it and copy word_frequency.py, word_frequency_test.py, and sample.txt from this repository into it.
- [ ] Normal Mode
  - [x] Open `sample.txt` and read in the text
  - [x] Count the number of times each word is used, regardless of capitalization
  - [ ] Find the top 20 words used and output them and their frequency to stdout
  - [ ] Run word_frequency_test.py and ensure you pass all the tests
- [ ] Hard Mode (optional)
  - [ ] Add a list of ignored words and don't count these in the word frequencies
  - [ ] Make your program take the name of the file to read on the command line, so it doesn't just have to work with `sample.txt`.
- [ ] Nightmare Mode (optional)
  - [ ] Output the top 20 words' frequencies using a simple text-based histogram
  - [ ] Normalize the histogram so there are never more than 50 `#` marks.

**Comment by kasalak** [comment]
https://github.com/kasalak/frequency-filer

got a count of the words used, but haven't gotten it to pass tests or work on the sample.txt file. 

@jamesmallen 
@powder-river

**Comment by powder-river** [comment]
@jamesmallen @kasalak let's get together and talk at some point today with either james or myself. right now your program spits out a massive dictionary and an ordered list of words. you don't have your code in a function so your test suite will not run there is also an error in your program as well.
