### ISSUE TITLE
04 -- Frequency Filer -- Will Butts

### ISSUE THREAD

**Issue by Shea-Wolfe** [tiyd-python-2015-08/assigments#82]
- [x] Blank slate
  - [x] Create a GitHub repo called `frequency-filer`
  - [x] Put a `README.md` file in it and copy word_frequency.py, word_frequency_test.py, and sample.txt from this repository into it.
- [x] Normal Mode
  - [x] Open `sample.txt` and read in the text
  - [x] Count the number of times each word is used, regardless of capitalization
  - [x] Find the top 20 words used and output them and their frequency to stdout
  - [x] Run word_frequency_test.py and ensure you pass all the tests
- [x] Hard Mode (optional)
  - [x] Add a list of ignored words and don't count these in the word frequencies
  - [x] Make your program take the name of the file to read on the command line, so it doesn't just have to work with `sample.txt`.
- [x] Nightmare Mode (optional)
  - [x] Output the top 20 words' frequencies using a simple text-based histogram
  - [x] Normalize the histogram so there are never more than 50 `#` marks.

**Comment by Shea-Wolfe** [comment]
@powder-river @jamesmallen 

https://github.com/Shea-Wolfe/frequency-filer

Got my MVP up.  Still kicking around hard and nightmare.  

Need to update my README but I wanted to get something here.

**Comment by powder-river** [comment]
@Shea-Wolfe so we talked about your load times. something to keep in mind for future projects. everything else looks solid, code works, tests pass, it's a good day

**Comment by Shea-Wolfe** [comment]
I optimized my code working from a base suggested by @powder-river and that I saw @gmhurley using when we were discussing nightmare_mode.  Now instead of counting every object in the dictionary for every single word it just iterates through the dictionaries.  I also completed hard and nightmare_mode (yay math!)
