### ISSUE TITLE
04 -- Frequency Filer -- Bob Amand

### ISSUE THREAD

**Issue by BobAmand** [tiyd-python-2015-08/assigments#85]
- [x] Blank slate
  - [x] Create a GitHub repo called `frequency-filer`
  - [x] Put a `README.md` file in it and copy word_frequency.py, word_frequency_test.py, and sample.txt from this repository into it.
- [ ] Normal Mode
  - [x] Open `sample.txt` and read in the text
  - [x] Count the number of times each word is used, regardless of capitalization
  - [ ] Find the top 20 words used and output them and their frequency to stdout
  - [ ] Run word_frequency_test.py and ensure you pass all the tests
- [ ] Hard Mode (optional)
  - [ ] Add a list of ignored words and don't count these in the word frequencies
  - [ ] Make your program take the name of the file to read on the command line, so it doesn't just have to work with `sample.txt`.
- [ ] Nightmare Mode (optional)
  - [ ] Output the top 20 words' frequencies using a simple text-based histogram
  - [ ] Normalize the histogram so there are never more than 50 `#` marks.

**Comment by BobAmand** [comment]
https://github.com/BobAmand/frequency-filer
@powder-river @jamesmallen 
Status:
1. Data passes into the word_frequency.py.  Seen in intermediate print steps.
2. Code written for all tasks through Normal Mode.  
3. Data stops processing at a unique word list.  
4. Downstream loops had been throwing a TypeError (integer vs str) which have been cleared.
5. Unable to see results of the test.py files.

Technical issues from home internet connection prevented sending before 12:30 am; failed attempts from 11:30 on.  Also, my existing issue had been removed by someone other than me.  This is a re-issue.    Thanks, Bob

**Comment by powder-river** [comment]
@jamesmallen @BobAmand something went wrong in a push somewhere, you don't have anything except the code from the initial repo let's get your code pushed to your repo

**Comment by powder-river** [comment]
@jamesmallen @BobAmand we sat down and looked at your HW together, lets get together today and further discuss any other questions you have
