### ISSUE TITLE
05 --  Mystery Word -- Andrew Pierce

### ISSUE THREAD

**Issue by andrewmpierce** [tiyd-python-2015-08/assigments#87]
- [x] Blank slate
  - [x] Create a GitHub repo called `mystery-word`
  - [x] Put a `README.md` file in it and copy mystery_word.py and mystery_word_test.py from this repository into it.
- [x] Normal Mode
  - [x] Load words from `/usr/share/dict/words`
  - [x] Write functions to select a subset of the complete word list
  - [x] Write a function to select a word at random from the word list
  - [x] Write a function to display a word with blanks/letters filled in the appropriate spots
  - [x] Write a function to check if a word has been completely guessed
  - [x] Write other helper functions as necessary to help with the flow of the game
  - [x] Run mystery_word_test.py and ensure you pass all the tests
- [ ] Hard Mode (optional)
  - [ ] Implement the evil version of the game and put it in evil_mystery_word.py
  - [ ] Write tests and put them in evil_mystery_word_tests.py

**Comment by andrewmpierce** [comment]
Submitted!
@jamesmallen 
@powder-river 
https://github.com/apierce1992/Mystery-Word
I will be working on nightmare mode and refactoring the normal mode code as the weekend progresses.

**Comment by powder-river** [comment]
@apierce1992 great work on the first weekend assignment. I do have some comments for you so let's get to it.
1. `What difficulty setting do you want?` see that prompt? guess what happened when I typed in "banana"? From the user perspective they have no instructions as to what to do here
2. There is no print out to show me what letters i have guessed. Make's it harder on the user.
3. This printout `You have 6 incorrect guesses left.` doesn't really make sense. Take out the `incorrect` and it will.

Overall excellent job, a few user interface things to tweak but all tests pass and everything runs smooth, well done! Enjoy the weekend

**Comment by andrewmpierce** [comment]
@powder-river 
Thanks for the comments! I definitely see your point in overlooking some of the user friendliness aspects and its something I'll keep on the lookout for on future assignments. It misses the forest because of all the trees. Ultimately a game is about the player, really.
