### ISSUE TITLE
05 -- Mystery-Word -- Kathleen Rauh

### ISSUE THREAD

**Issue by nckathleen** [tiyd-python-2015-08/assigments#88]
- [x] Blank slate
  - [x] Create a GitHub repo called `mystery-word`
  - [x] Put a `README.md` file in it and copy mystery_word.py and mystery_word_test.py from this repository into it.
- [x] Normal Mode
  - [x] Load words from `/usr/share/dict/words`
  - [x] Write functions to select a subset of the complete word list
  - [x] Write a function to select a word at random from the word list
  - [x] Write a function to display a word with blanks/letters filled in the appropriate spots
  - [x] Write a function to check if a word has been completely guessed
  - [x] Write other helper functions as necessary to help with the flow of the game
  - [x] Run mystery_word_test.py and ensure you pass all the tests
- [ ] Hard Mode (optional)
  - [ ] Implement the evil version of the game and put it in evil_mystery_word.py
  - [ ] Write tests and put them in evil_mystery_word_tests.py

**Comment by nckathleen** [comment]
https://github.com/nckathleen/Mystery-Word/blob/master/mystery_word.py
Phew! Normal mode.
@jamesmallen @powder-river

**Comment by powder-river** [comment]
@nckathleen Strong Submission! You took the route of creating more functions which is totally a valid one. LOVING the readme.md good explanation of how to run and what it does. Just know that you could have done it without creating your own functions, but by all means your way is perfectly fine. Really good submission Kathleen!
