### ISSUE TITLE
05 -- Mystery-Word -- Bob Amand

### ISSUE THREAD

**Issue by BobAmand** [tiyd-python-2015-08/assigments#90]
- [x] Blank slate
  - [x] Create a GitHub repo called `mystery-word`
  - [x] Put a `README.md` file in it and copy mystery_word.py and mystery_word_test.py from this repository into it.
- [x] Normal Mode
  - [x] Load words from `/usr/share/dict/words`
  - [x] Write functions to select a subset of the complete word list
  - [x] Write a function to select a word at random from the word list
  - [x] Write a function to display a word with blanks/letters filled in the appropriate spots
  - [x] Write a function to check if a word has been completely guessed
  - [ ] Write other helper functions as necessary to help with the flow of the game
  - [x] Run mystery_word_test.py and ensure you pass all the tests
- [ ] Hard Mode (optional)
  - [ ] Implement the evil version of the game and put it in evil_mystery_word.py
  - [ ] Write tests and put them in evil_mystery_word_tests.py

**Comment by BobAmand** [comment]
https://github.com/BobAmand/mystery_word
@powder-river  @jamesmallen

**Comment by powder-river** [comment]
@BobAmand your code doesn't appear to return anything in the shell. Also it looks like your tests are failing

**Comment by BobAmand** [comment]
https://github.com/BobAmand/mystery_word

Did not push!!!  So sorry.  
1. last version Fails 1 test.
2. previous version Passed all.  Then I went in to tweak, and now 1 fails.
@powder-river  @jamesmallen
