### ISSUE TITLE
05 -- Mystery-Word -- Glenn Hurley

### ISSUE THREAD

**Issue by gmhurley** [tiyd-python-2015-08/assigments#91]
- [x] Blank slate
  - [x] Create a GitHub repo called `mystery-word`
  - [x] Put a `README.md` file in it and copy mystery_word.py and mystery_word_test.py from this repository into it.
- [x] Normal Mode
  - [x] Load words from `/usr/share/dict/words`
  - [x] Write functions to select a subset of the complete word list
  - [x] Write a function to select a word at random from the word list
  - [x] Write a function to display a word with blanks/letters filled in the appropriate spots
  - [x] Write a function to check if a word has been completely guessed
  - [x] Write other helper functions as necessary to help with the flow of the game
  - [x] Run mystery_word_test.py and ensure you pass all the tests
- [x] Hard Mode (optional)
  - [x] Implement the evil version of the game and put it in evil_mystery_word.py
  - [x] Write tests and put them in evil_mystery_word_tests.py

**Comment by gmhurley** [comment]
https://github.com/gmhurley/mystery-word/tree/normal
@jamesmallen 
@powder-river

**Comment by powder-river** [comment]
@gmhurley code is solid man, loving the README. Only comment would be remember that when you write a commit message, you are essentially writing a message to your future self to state what the status of your code is at that time. I know this was still a fairly reasonable project just keep in mind moving forward to commit often. every time you get something working, do a quick commit. Good Job Glenn!

**Comment by gmhurley** [comment]
@powder-river @jamesmallen 
https://github.com/gmhurley/mystery-word/blob/master/evil_mystery_word.py

Hard mode. Will write the tests later today.

**Comment by gmhurley** [comment]
@powder-river @jamesmallen 
Added a test and fixed bug in evil mode.
