### ISSUE TITLE
05 -- Mystery Word -- Will Butts

### ISSUE THREAD

**Issue by Shea-Wolfe** [tiyd-python-2015-08/assigments#95]
- [x] Blank slate
  - [x] Create a GitHub repo called `mystery-word`
  - [x] Put a `README.md` file in it and copy mystery_word.py and mystery_word_test.py from this repository into it.
- [x] Normal Mode
  - [x] Load words from `/usr/share/dict/words`
  - [x] Write functions to select a subset of the complete word list
  - [x] Write a function to select a word at random from the word list
  - [x] Write a function to display a word with blanks/letters filled in the appropriate spots
  - [x] Write a function to check if a word has been completely guessed
  - [x] Write other helper functions as necessary to help with the flow of the game
  - [x] Run mystery_word_test.py and ensure you pass all the tests
- [ ] Hard Mode (optional)
  - [x] Implement the evil version of the game and put it in evil_mystery_word.py
  - [ ] Write tests and put them in evil_mystery_word_tests.py

**Comment by Shea-Wolfe** [comment]
@powder-river @jamesmallen 

Got the game working.  Need to update my README but am done for the night.

https://github.com/Shea-Wolfe/mystery-word

**Comment by powder-river** [comment]
@Shea-Wolfe great program, runs well, passes tests ,does what it needs to do. Let's talk about making commits. You have 7 of them, 5 of which are just moving files around/housekeeping. Make sure you start getting in the habit of committing often. every time you get something to work, commit it. see how your first commit is "passes all tests". There should be a series of commits leading up to that point. Learn that habit early and you'll go far. Excellent work on this assignment, very well done!
