### ISSUE TITLE
05--Mystery Word-- Michael Krawiec

### ISSUE THREAD

**Issue by msk007** [tiyd-python-2015-08/assigments#96]
- [x] Blank slate
  - [x] Create a GitHub repo called `mystery-word`
  - [x] Put a `README.md` file in it and copy mystery_word.py and mystery_word_test.py from this repository into it.
- [ ] Normal Mode
  - [x] Load words from `/usr/share/dict/words`
  - [x] Write functions to select a subset of the complete word list
  - [x] Write a function to select a word at random from the word list
  - [x] Write a function to display a word with blanks/letters filled in the appropriate spots
  - [x] Write a function to check if a word has been completely guessed
  - [ ] Write other helper functions as necessary to help with the flow of the game
  - [ ] Run mystery_word_test.py and ensure you pass all the tests
- [ ] Hard Mode (optional)
  - [ ] Implement the evil version of the game and put it in evil_mystery_word.py
  - [ ] Write tests and put them in evil_mystery_word_tests.py

**Comment by msk007** [comment]
https://github.com/msk007/Mystery-Word/blob/master/mystery_word.py

Ok. I got stuck at the game loop and im so very tired. I feel like i'm getting close and would like to finish tomorrow at lab and re-submit.
I would like to take some comfort in small victories. For the first time i feel like i've gotten a decent handle on git/github and i was able to make several commits and document what i was doing so hopefully you can see my thought process/workflow a little better and maybe that will in tern help me out. 
I got stuck on making the loop. not sure where to go from where i am and time has run out.

SUBMIT
@powder-river 
@jamesmallen

**Comment by powder-river** [comment]
@msk007 right so don't forget about having a MVP to have at least something that run. if you can get some things working let me know and we'll take another look at it.
