### ISSUE TITLE
06 -- Game-of-Sticks -- Bob Amand

### ISSUE THREAD

**Issue by BobAmand** [tiyd-python-2015-08/assigments#99]
- [x] Blank slate
  - [x] Create a GitHub repo called `game-of-sticks`
  - [x] Put a `README.md` file in it and copy mystery_word.py and mystery_word_test.py from this repository into it.
- [x] Normal Mode
  - [x] Player vs Player
    - [x] Decide on the data structure(s) that you are going to need to use to represent the state of the game when played
    - [x] Decide on the tasks that will be part of the game loop
    - [x] Write test functions for each of the tasks
    - [x] Write functions for each of the tasks and make sure they pass your tests
  - [ ] Player vs AI
    - [x] Decide on the data structure(s) that you are going to need to use to represent the additional state of the artificial intelligence
    - [ ] Write functions to assist with each of the tasks of the AI
    - [ ] Modify your game loop/main funciton to allow for the AI to play
    - [ ] Make sure that your AI actually does get better over time - play a few games against it. You may want to add some extra debugging output to keep an eye on the hats
- [ ] Hard Mode
  - [ ] Modify your program to allow for AI to play against AI
  - [ ] Give the human player the option to battle against the AI from normal mode or a pre-trained AI that has played a large number of simulated games
  - [ ] Examine the contents of the hats for the pre-trained AI, and see if you can determine its strategy
- [ ] Nightmare Mode
  - [ ] Write a Tic-Tac-Toe program that pre-trains its AI using the same strategy as **Hard Mode**.

**Comment by BobAmand** [comment]
https://github.com/BobAmand/game-of-sticks
@powder-river  @jamesmallen 

Too little time left for solving the good stuff.   Wrestling with dictionary.append/.remove while accumulating performance numbers.

**Comment by powder-river** [comment]
@jamesmallen @BobAmand it looks like your game actually goes below 0 sticks and the person to remove sticks after it's gone bellow 0 loses. I you don't get your questions answered during HW review feel free to slack me and we can set aside time today to work together
